import { resetCompositionRoot } from "../../../core/composition/createCompositionRoot";
import { RuntimeBootstrap, resetRuntimeBootstrap } from "../../bootstrap/RuntimeBootstrap";
import { hydrateRuntime, getHydrationStatus } from "../application";
import { HYDRATION_PHASES } from "../HydrationInitialization";
import { HYDRATION_STATUS } from "../HydrationStatus";
import {
  RepositoryHydrationPipeline,
  resetRepositoryHydration,
} from "../RepositoryHydrationPipeline";
import { HydrationError } from "../HydrationError";
import {
  FIXED_DASHBOARD_ATHLETE_ID,
} from "../../../integrations/dashboard-projection/testSupport/fixtures";
import {
  createHydrationTestDeps,
  createMockRuntimeRepositories,
  createSeededHydrationRecords,
  createTestRuntimeServices,
  seedTestRuntimeDomainState,
} from "../../testSupport/runtimePersistenceFixtures";

const TEST_ATHLETE_ID = FIXED_DASHBOARD_ATHLETE_ID;

describe("RepositoryHydrationPipeline", () => {
  afterEach(() => {
    resetRepositoryHydration();
    resetRuntimeBootstrap();
    resetCompositionRoot();
  });

  it("hydrates runtime from repository contracts after bootstrap completes", async () => {
    RuntimeBootstrap.bootstrap({
      clock: () => "2026-08-10T10:00:00.000Z",
    });

    const services = createTestRuntimeServices(
      () => "2026-08-10T10:00:01.000Z",
    );
    seedTestRuntimeDomainState(services, TEST_ATHLETE_ID, () =>
      "2026-08-10T10:00:01.000Z",
    );
    const records = createSeededHydrationRecords(services, TEST_ATHLETE_ID);

    const result = await RepositoryHydrationPipeline.hydrate({
      deps: {
        ...createMockRuntimeRepositories(records),
        ...services,
        clock: () => "2026-08-10T10:00:01.000Z",
      },
    });

    expect(result.status).toBe("ready");
    expect(result.identityRecordCount).toBe(1);
    expect(result.runtimeRecordCount).toBe(1);
    expect(result.workspaceRecordCount).toBe(1);
    expect(result.restoredAt).toBe("2026-08-10T10:00:01.000Z");
    expect(result.phases).toEqual([...HYDRATION_PHASES]);
    expect(getHydrationStatus()).toBe(HYDRATION_STATUS.ready);

    const identity = services.athleteIdentityService.getAthleteIdentity(TEST_ATHLETE_ID);
    const runtime = services.runtimeEnvironmentService.getRuntimeEnvironment();
    const workspace = services.unifiedWorkspaceService.getWorkspace(TEST_ATHLETE_ID);
    const timeline = services.coachTimelineService.getTimeline(TEST_ATHLETE_ID);

    expect(identity?.profile.displayName).toBe("Alex Athlete");
    expect(runtime?.device.model).toBe("Test Device");
    expect(workspace).not.toBeNull();
    expect(timeline?.entryCount).toBeGreaterThanOrEqual(1);
  });

  it("restores the identity's own id/createdAt/metadata verbatim across a hydrate into a fresh service instance (Sprint 36.6)", async () => {
    RuntimeBootstrap.bootstrap({
      clock: () => "2026-08-10T10:00:00.000Z",
    });

    const seedServices = createTestRuntimeServices(
      () => "2026-08-10T10:00:01.000Z",
    );
    const { identity: originalIdentity } = seedTestRuntimeDomainState(
      seedServices,
      TEST_ATHLETE_ID,
      () => "2026-08-10T10:00:01.000Z",
    );
    const records = createSeededHydrationRecords(seedServices, TEST_ATHLETE_ID);

    // Hydrate into a brand-new set of services (a fresh app restart), not
    // the same instance used to seed — proving a genuine persist -> reset
    // -> hydrate round trip rather than reading back an in-memory service
    // that never lost the data in the first place.
    const freshServices = createTestRuntimeServices(
      () => "2026-08-10T20:00:00.000Z",
    );

    const result = await RepositoryHydrationPipeline.hydrate({
      deps: {
        ...createMockRuntimeRepositories(records),
        ...freshServices,
        clock: () => "2026-08-10T20:00:00.000Z",
      },
    });

    expect(result.status).toBe("ready");
    const restoredIdentity =
      freshServices.athleteIdentityService.getAthleteIdentity(TEST_ATHLETE_ID);

    expect(restoredIdentity).not.toBeNull();
    // The identity's own bookkeeping fields must survive the round trip
    // verbatim rather than being silently regenerated by hydration.
    expect(restoredIdentity?.id).toBe(originalIdentity?.id);
    expect(restoredIdentity?.createdAt).toBe(originalIdentity?.createdAt);
    expect(restoredIdentity?.metadata).toEqual(originalIdentity?.metadata);
    expect(restoredIdentity?.profile.displayName).toBe(
      originalIdentity?.profile.displayName,
    );
  });

  it("succeeds with an empty runtime when repositories return no records", async () => {
    RuntimeBootstrap.bootstrap();

    const deps = createHydrationTestDeps();

    const result = await RepositoryHydrationPipeline.hydrate({
      deps,
    });

    expect(result.identityRecordCount).toBe(0);
    expect(result.runtimeRecordCount).toBe(0);
    expect(result.workspaceRecordCount).toBe(0);
    expect(deps.athleteIdentityService.getAthleteIdentity("athlete:1")).toBeNull();
    expect(deps.runtimeEnvironmentService.getRuntimeEnvironment()).toBeNull();
    expect(deps.unifiedWorkspaceService.getWorkspace("athlete:1")).toBeNull();
  });

  it("rejects duplicate hydration attempts", async () => {
    RuntimeBootstrap.bootstrap();

    const deps = createHydrationTestDeps();

    await RepositoryHydrationPipeline.hydrate({ deps });

    await expect(RepositoryHydrationPipeline.hydrate({ deps })).rejects.toThrow(
      HydrationError,
    );
    await expect(RepositoryHydrationPipeline.hydrate({ deps })).rejects.toThrow(
      /already started/i,
    );
  });

  it("requires runtime bootstrap before hydration", async () => {
    await expect(
      RepositoryHydrationPipeline.hydrate({
        deps: createHydrationTestDeps(),
      }),
    ).rejects.toThrow(HydrationError);

    await expect(
      RepositoryHydrationPipeline.hydrate({
        deps: createHydrationTestDeps(),
      }),
    ).rejects.toThrow(/bootstrap must complete/i);
  });

  it("exposes hydrateRuntime as an idempotent application API", async () => {
    RuntimeBootstrap.bootstrap({
      clock: () => "2026-08-10T10:00:00.000Z",
    });

    const first = await hydrateRuntime();
    const second = await hydrateRuntime();

    expect(second).toBe(first);
    expect(getHydrationStatus()).toBe(HYDRATION_STATUS.ready);
  });
});
