/**
 * Deterministic coach insight types (Sprint 25.5).
 * Derived only from existing domain evidence — never invented.
 */
export const CoachInsightTypes = {
  FATIGUE_PATTERN: "FATIGUE_PATTERN",
  RECOVERY_DECLINE: "RECOVERY_DECLINE",
  WORKOUT_COMPLIANCE: "WORKOUT_COMPLIANCE",
  NUTRITION_COMPLIANCE: "NUTRITION_COMPLIANCE",
  GOAL_STALL: "GOAL_STALL",
  GOAL_ACCELERATION: "GOAL_ACCELERATION",
  TRAINING_VOLUME: "TRAINING_VOLUME",
  TRAINING_INTENSITY: "TRAINING_INTENSITY",
  MISSED_SESSIONS: "MISSED_SESSIONS",
  MISSED_MEALS: "MISSED_MEALS",
  RECOVERY_IMPROVEMENT: "RECOVERY_IMPROVEMENT",
  PROGRAM_CONSISTENCY: "PROGRAM_CONSISTENCY",
  PREFERENCE_PATTERN: "PREFERENCE_PATTERN",
  MODIFICATION_PATTERN: "MODIFICATION_PATTERN",
  RESTORE_PATTERN: "RESTORE_PATTERN",
  LONG_TERM_PROGRESS: "LONG_TERM_PROGRESS",
  PLATEAU_RISK: "PLATEAU_RISK",
  OVERREACH_RISK: "OVERREACH_RISK",
  UNDERTRAINING_RISK: "UNDERTRAINING_RISK",
  UNKNOWN: "UNKNOWN",
} as const;

export type CoachInsightType =
  (typeof CoachInsightTypes)[keyof typeof CoachInsightTypes];

export const ALL_COACH_INSIGHT_TYPES: readonly CoachInsightType[] =
  Object.freeze(Object.values(CoachInsightTypes));
