import type { ExerciseDefinition } from "../models/ExerciseDefinition";
import { createExerciseDefinition } from "../testSupport/fixtures";

/**
 * Illustrative in-memory catalog (~25 exercises).
 * Architecture supports thousands; this set is for tests and local orchestration.
 */
export const ILLUSTRATIVE_EXERCISE_CATALOG: readonly ExerciseDefinition[] =
  Object.freeze([
    createExerciseDefinition({
      id: "back-squat",
      name: "Back Squat",
      movementPattern: "squat",
      primaryMuscles: ["quads"],
      secondaryMuscles: ["glutes", "core", "lower_back"],
      equipment: ["barbell"],
      difficulty: "intermediate",
      skillScore: 6,
      pushPullLegs: "legs",
      fatigueScore: 9,
      jointStress: 7,
      axialLoading: true,
      tags: [
        "squat_pattern",
        "lower_body",
        "bilateral",
        "free_weight",
        "axial_loading",
        "competition_lift",
      ],
      contraindications: ["acute_knee_pain", "acute_lumbar_pain"],
      constraints: [
        { kind: "contraindication", code: "acute_knee_pain", severity: "hard" },
        { kind: "axial", code: "spinal_loading", severity: "soft" },
      ],
      relationships: [
        { kind: "alternative", targetExerciseId: "front-squat", strength: 0.85 },
        {
          kind: "alternative",
          targetExerciseId: "safety-bar-squat",
          strength: 0.9,
        },
        { kind: "alternative", targetExerciseId: "leg-press", strength: 0.7 },
        { kind: "alternative", targetExerciseId: "hack-squat", strength: 0.75 },
        {
          kind: "variation",
          targetExerciseId: "paused-squat",
          strength: 0.95,
        },
        {
          kind: "progression",
          targetExerciseId: "paused-squat",
          strength: 0.8,
        },
        {
          kind: "regression",
          targetExerciseId: "leg-press",
          strength: 0.7,
        },
      ],
      variants: [
        { id: "high-bar", name: "High Bar Back Squat", noteCode: "high_bar" },
        { id: "low-bar", name: "Low Bar Back Squat", noteCode: "low_bar" },
      ],
    }),
    createExerciseDefinition({
      id: "front-squat",
      name: "Front Squat",
      movementPattern: "squat",
      primaryMuscles: ["quads"],
      secondaryMuscles: ["glutes", "core", "upper_back"],
      equipment: ["barbell"],
      difficulty: "advanced",
      skillScore: 7,
      pushPullLegs: "legs",
      fatigueScore: 8,
      jointStress: 6,
      axialLoading: true,
      tags: [
        "squat_pattern",
        "lower_body",
        "bilateral",
        "free_weight",
        "axial_loading",
        "advanced",
      ],
      relationships: [
        { kind: "alternative", targetExerciseId: "back-squat", strength: 0.85 },
        {
          kind: "alternative",
          targetExerciseId: "safety-bar-squat",
          strength: 0.8,
        },
        { kind: "regression", targetExerciseId: "goblet-squat", strength: 0.75 },
      ],
    }),
    createExerciseDefinition({
      id: "safety-bar-squat",
      name: "Safety Bar Squat",
      movementPattern: "squat",
      primaryMuscles: ["quads"],
      secondaryMuscles: ["glutes", "core", "upper_back"],
      equipment: ["safety_bar"],
      difficulty: "intermediate",
      skillScore: 5,
      pushPullLegs: "legs",
      fatigueScore: 8,
      jointStress: 6,
      axialLoading: true,
      tags: [
        "squat_pattern",
        "lower_body",
        "bilateral",
        "free_weight",
        "axial_loading",
        "shoulder_friendly",
      ],
      relationships: [
        { kind: "alternative", targetExerciseId: "back-squat", strength: 0.9 },
        { kind: "alternative", targetExerciseId: "front-squat", strength: 0.8 },
      ],
    }),
    createExerciseDefinition({
      id: "paused-squat",
      name: "Paused Squat",
      movementPattern: "squat",
      primaryMuscles: ["quads"],
      secondaryMuscles: ["glutes", "core", "lower_back"],
      equipment: ["barbell"],
      difficulty: "advanced",
      skillScore: 7,
      pushPullLegs: "legs",
      fatigueScore: 9,
      jointStress: 7,
      axialLoading: true,
      tags: [
        "squat_pattern",
        "lower_body",
        "bilateral",
        "free_weight",
        "axial_loading",
        "variation",
        "advanced",
      ],
      relationships: [
        { kind: "variation", targetExerciseId: "back-squat", strength: 0.95 },
        { kind: "regression", targetExerciseId: "back-squat", strength: 0.85 },
      ],
    }),
    createExerciseDefinition({
      id: "goblet-squat",
      name: "Goblet Squat",
      movementPattern: "squat",
      primaryMuscles: ["quads"],
      secondaryMuscles: ["glutes", "core"],
      equipment: ["dumbbell"],
      difficulty: "beginner",
      skillScore: 2,
      pushPullLegs: "legs",
      fatigueScore: 4,
      jointStress: 4,
      axialLoading: false,
      tags: [
        "squat_pattern",
        "lower_body",
        "bilateral",
        "free_weight",
        "beginner_friendly",
        "low_axial",
      ],
      relationships: [
        { kind: "progression", targetExerciseId: "front-squat", strength: 0.75 },
        { kind: "alternative", targetExerciseId: "leg-press", strength: 0.6 },
      ],
    }),
    createExerciseDefinition({
      id: "bench-press",
      name: "Bench Press",
      movementPattern: "horizontal_push",
      primaryMuscles: ["chest"],
      secondaryMuscles: ["triceps", "shoulders"],
      equipment: ["barbell"],
      difficulty: "intermediate",
      skillScore: 5,
      pushPullLegs: "push",
      fatigueScore: 7,
      jointStress: 6,
      axialLoading: false,
      tags: [
        "press",
        "upper_body",
        "bilateral",
        "free_weight",
        "competition_lift",
      ],
      contraindications: ["acute_shoulder_pain"],
      constraints: [
        {
          kind: "contraindication",
          code: "acute_shoulder_pain",
          severity: "hard",
        },
      ],
      relationships: [
        {
          kind: "alternative",
          targetExerciseId: "incline-bench",
          strength: 0.8,
        },
        {
          kind: "alternative",
          targetExerciseId: "close-grip-bench",
          strength: 0.75,
        },
        {
          kind: "alternative",
          targetExerciseId: "dumbbell-bench-press",
          strength: 0.85,
        },
        {
          kind: "variation",
          targetExerciseId: "close-grip-bench",
          strength: 0.9,
        },
      ],
      variants: [
        {
          id: "paused-bench",
          name: "Paused Bench Press",
          noteCode: "paused",
        },
      ],
    }),
    createExerciseDefinition({
      id: "incline-bench",
      name: "Incline Bench",
      movementPattern: "horizontal_push",
      primaryMuscles: ["chest", "shoulders"],
      secondaryMuscles: ["triceps"],
      equipment: ["barbell"],
      difficulty: "intermediate",
      skillScore: 5,
      pushPullLegs: "push",
      fatigueScore: 6,
      jointStress: 6,
      axialLoading: false,
      tags: ["press", "upper_body", "bilateral", "free_weight", "accessory"],
      relationships: [
        { kind: "alternative", targetExerciseId: "bench-press", strength: 0.8 },
        {
          kind: "alternative",
          targetExerciseId: "overhead-press",
          strength: 0.55,
        },
      ],
    }),
    createExerciseDefinition({
      id: "close-grip-bench",
      name: "Close Grip Bench",
      movementPattern: "horizontal_push",
      primaryMuscles: ["triceps", "chest"],
      secondaryMuscles: ["shoulders"],
      equipment: ["barbell"],
      difficulty: "intermediate",
      skillScore: 5,
      pushPullLegs: "push",
      fatigueScore: 6,
      jointStress: 5,
      axialLoading: false,
      tags: ["press", "upper_body", "bilateral", "free_weight", "variation"],
      relationships: [
        { kind: "variation", targetExerciseId: "bench-press", strength: 0.9 },
        { kind: "alternative", targetExerciseId: "bench-press", strength: 0.75 },
      ],
    }),
    createExerciseDefinition({
      id: "dumbbell-bench-press",
      name: "Dumbbell Bench Press",
      movementPattern: "horizontal_push",
      primaryMuscles: ["chest"],
      secondaryMuscles: ["triceps", "shoulders"],
      equipment: ["dumbbell"],
      difficulty: "beginner",
      skillScore: 3,
      pushPullLegs: "push",
      fatigueScore: 5,
      jointStress: 4,
      axialLoading: false,
      tags: [
        "press",
        "upper_body",
        "bilateral",
        "free_weight",
        "beginner_friendly",
        "shoulder_friendly",
      ],
      relationships: [
        { kind: "alternative", targetExerciseId: "bench-press", strength: 0.85 },
        {
          kind: "progression",
          targetExerciseId: "bench-press",
          strength: 0.7,
        },
      ],
    }),
    createExerciseDefinition({
      id: "overhead-press",
      name: "Overhead Press",
      movementPattern: "vertical_push",
      primaryMuscles: ["shoulders"],
      secondaryMuscles: ["triceps", "core"],
      equipment: ["barbell"],
      difficulty: "intermediate",
      skillScore: 6,
      pushPullLegs: "push",
      fatigueScore: 7,
      jointStress: 7,
      axialLoading: true,
      tags: [
        "press",
        "upper_body",
        "bilateral",
        "free_weight",
        "axial_loading",
        "competition_lift",
      ],
      relationships: [
        {
          kind: "alternative",
          targetExerciseId: "incline-bench",
          strength: 0.55,
        },
      ],
    }),
    createExerciseDefinition({
      id: "deadlift",
      name: "Deadlift",
      movementPattern: "hinge",
      primaryMuscles: ["hamstrings", "lower_back"],
      secondaryMuscles: ["glutes", "traps", "forearms"],
      equipment: ["barbell"],
      difficulty: "intermediate",
      skillScore: 6,
      pushPullLegs: "legs",
      fatigueScore: 10,
      jointStress: 8,
      axialLoading: true,
      tags: [
        "hinge_pattern",
        "lower_body",
        "posterior_chain",
        "bilateral",
        "free_weight",
        "axial_loading",
        "competition_lift",
      ],
      contraindications: ["acute_lumbar_pain"],
      constraints: [
        {
          kind: "contraindication",
          code: "acute_lumbar_pain",
          severity: "hard",
        },
        { kind: "axial", code: "spinal_loading", severity: "hard" },
      ],
      relationships: [
        {
          kind: "alternative",
          targetExerciseId: "romanian-deadlift",
          strength: 0.75,
        },
        {
          kind: "alternative",
          targetExerciseId: "sumo-deadlift",
          strength: 0.85,
        },
        {
          kind: "variation",
          targetExerciseId: "sumo-deadlift",
          strength: 0.9,
        },
        {
          kind: "regression",
          targetExerciseId: "romanian-deadlift",
          strength: 0.65,
        },
      ],
    }),
    createExerciseDefinition({
      id: "romanian-deadlift",
      name: "Romanian Deadlift",
      movementPattern: "hinge",
      primaryMuscles: ["hamstrings"],
      secondaryMuscles: ["glutes", "lower_back"],
      equipment: ["barbell"],
      difficulty: "intermediate",
      skillScore: 5,
      pushPullLegs: "legs",
      fatigueScore: 6,
      jointStress: 6,
      axialLoading: true,
      tags: [
        "hinge_pattern",
        "lower_body",
        "posterior_chain",
        "bilateral",
        "free_weight",
        "axial_loading",
        "accessory",
      ],
      relationships: [
        { kind: "alternative", targetExerciseId: "deadlift", strength: 0.75 },
        {
          kind: "alternative",
          targetExerciseId: "leg-curl",
          strength: 0.55,
        },
        { kind: "progression", targetExerciseId: "deadlift", strength: 0.7 },
      ],
    }),
    createExerciseDefinition({
      id: "sumo-deadlift",
      name: "Sumo Deadlift",
      movementPattern: "hinge",
      primaryMuscles: ["glutes", "quads"],
      secondaryMuscles: ["hamstrings", "lower_back", "adductors"],
      equipment: ["barbell"],
      difficulty: "intermediate",
      skillScore: 6,
      pushPullLegs: "legs",
      fatigueScore: 9,
      jointStress: 7,
      axialLoading: true,
      tags: [
        "hinge_pattern",
        "lower_body",
        "posterior_chain",
        "bilateral",
        "free_weight",
        "axial_loading",
        "variation",
      ],
      relationships: [
        { kind: "variation", targetExerciseId: "deadlift", strength: 0.9 },
        { kind: "alternative", targetExerciseId: "deadlift", strength: 0.85 },
      ],
    }),
    createExerciseDefinition({
      id: "barbell-row",
      name: "Barbell Row",
      movementPattern: "horizontal_pull",
      primaryMuscles: ["upper_back", "lats"],
      secondaryMuscles: ["biceps", "traps"],
      equipment: ["barbell"],
      difficulty: "intermediate",
      skillScore: 5,
      pushPullLegs: "pull",
      fatigueScore: 6,
      jointStress: 5,
      axialLoading: true,
      tags: [
        "row",
        "pull",
        "upper_body",
        "bilateral",
        "free_weight",
        "axial_loading",
      ],
      relationships: [
        {
          kind: "alternative",
          targetExerciseId: "chest-supported-row",
          strength: 0.85,
        },
        { kind: "alternative", targetExerciseId: "pull-up", strength: 0.5 },
        {
          kind: "regression",
          targetExerciseId: "chest-supported-row",
          strength: 0.8,
        },
      ],
    }),
    createExerciseDefinition({
      id: "chest-supported-row",
      name: "Chest Supported Row",
      movementPattern: "horizontal_pull",
      primaryMuscles: ["upper_back", "lats"],
      secondaryMuscles: ["biceps"],
      equipment: ["dumbbell"],
      difficulty: "beginner",
      skillScore: 3,
      pushPullLegs: "pull",
      fatigueScore: 4,
      jointStress: 3,
      axialLoading: false,
      tags: [
        "row",
        "pull",
        "upper_body",
        "bilateral",
        "free_weight",
        "beginner_friendly",
        "low_axial",
      ],
      relationships: [
        { kind: "alternative", targetExerciseId: "barbell-row", strength: 0.85 },
        {
          kind: "progression",
          targetExerciseId: "barbell-row",
          strength: 0.75,
        },
      ],
    }),
    createExerciseDefinition({
      id: "pull-up",
      name: "Pull Up",
      movementPattern: "vertical_pull",
      primaryMuscles: ["lats"],
      secondaryMuscles: ["biceps", "upper_back"],
      equipment: ["bodyweight"],
      difficulty: "intermediate",
      skillScore: 6,
      pushPullLegs: "pull",
      fatigueScore: 6,
      jointStress: 5,
      axialLoading: false,
      tags: [
        "pull",
        "upper_body",
        "bilateral",
        "bodyweight",
        "low_axial",
      ],
      relationships: [
        {
          kind: "alternative",
          targetExerciseId: "lat-pulldown",
          strength: 0.9,
        },
        {
          kind: "regression",
          targetExerciseId: "lat-pulldown",
          strength: 0.85,
        },
      ],
    }),
    createExerciseDefinition({
      id: "lat-pulldown",
      name: "Lat Pulldown",
      movementPattern: "vertical_pull",
      primaryMuscles: ["lats"],
      secondaryMuscles: ["biceps", "upper_back"],
      equipment: ["cable"],
      difficulty: "beginner",
      skillScore: 2,
      pushPullLegs: "pull",
      fatigueScore: 4,
      jointStress: 3,
      axialLoading: false,
      tags: [
        "pull",
        "upper_body",
        "bilateral",
        "machine",
        "beginner_friendly",
        "low_axial",
      ],
      relationships: [
        { kind: "alternative", targetExerciseId: "pull-up", strength: 0.9 },
        { kind: "progression", targetExerciseId: "pull-up", strength: 0.85 },
      ],
    }),
    createExerciseDefinition({
      id: "leg-press",
      name: "Leg Press",
      movementPattern: "squat",
      primaryMuscles: ["quads"],
      secondaryMuscles: ["glutes"],
      equipment: ["machine"],
      difficulty: "beginner",
      skillScore: 2,
      pushPullLegs: "legs",
      fatigueScore: 6,
      jointStress: 5,
      axialLoading: false,
      tags: [
        "squat_pattern",
        "lower_body",
        "bilateral",
        "machine",
        "beginner_friendly",
        "low_axial",
        "knee_friendly",
      ],
      relationships: [
        { kind: "alternative", targetExerciseId: "back-squat", strength: 0.7 },
        { kind: "alternative", targetExerciseId: "hack-squat", strength: 0.8 },
        {
          kind: "progression",
          targetExerciseId: "back-squat",
          strength: 0.65,
        },
      ],
    }),
    createExerciseDefinition({
      id: "hack-squat",
      name: "Hack Squat",
      movementPattern: "squat",
      primaryMuscles: ["quads"],
      secondaryMuscles: ["glutes"],
      equipment: ["machine"],
      difficulty: "intermediate",
      skillScore: 4,
      pushPullLegs: "legs",
      fatigueScore: 7,
      jointStress: 6,
      axialLoading: false,
      tags: [
        "squat_pattern",
        "lower_body",
        "bilateral",
        "machine",
        "low_axial",
        "anterior_chain",
      ],
      relationships: [
        { kind: "alternative", targetExerciseId: "back-squat", strength: 0.75 },
        { kind: "alternative", targetExerciseId: "leg-press", strength: 0.8 },
      ],
    }),
    createExerciseDefinition({
      id: "bulgarian-split-squat",
      name: "Bulgarian Split Squat",
      movementPattern: "lunge",
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["hamstrings", "core"],
      equipment: ["dumbbell"],
      difficulty: "intermediate",
      skillScore: 6,
      pushPullLegs: "legs",
      isUnilateral: true,
      fatigueScore: 7,
      jointStress: 6,
      axialLoading: false,
      tags: [
        "lower_body",
        "unilateral",
        "free_weight",
        "low_axial",
        "accessory",
      ],
      relationships: [
        { kind: "alternative", targetExerciseId: "back-squat", strength: 0.55 },
        { kind: "alternative", targetExerciseId: "leg-press", strength: 0.5 },
      ],
    }),
    createExerciseDefinition({
      id: "hip-thrust",
      name: "Hip Thrust",
      movementPattern: "hinge",
      primaryMuscles: ["glutes"],
      secondaryMuscles: ["hamstrings", "core"],
      equipment: ["barbell"],
      difficulty: "beginner",
      skillScore: 3,
      pushPullLegs: "legs",
      fatigueScore: 5,
      jointStress: 3,
      axialLoading: false,
      tags: [
        "hinge_pattern",
        "lower_body",
        "posterior_chain",
        "bilateral",
        "free_weight",
        "low_axial",
        "beginner_friendly",
      ],
      relationships: [
        {
          kind: "alternative",
          targetExerciseId: "romanian-deadlift",
          strength: 0.6,
        },
      ],
    }),
    createExerciseDefinition({
      id: "leg-curl",
      name: "Leg Curl",
      movementPattern: "isolation",
      primaryMuscles: ["hamstrings"],
      secondaryMuscles: [],
      equipment: ["machine"],
      difficulty: "beginner",
      skillScore: 1,
      category: "isolation",
      isCompound: false,
      pushPullLegs: "legs",
      fatigueScore: 3,
      jointStress: 2,
      axialLoading: false,
      tags: [
        "lower_body",
        "posterior_chain",
        "bilateral",
        "machine",
        "beginner_friendly",
        "low_axial",
        "accessory",
      ],
      relationships: [
        {
          kind: "alternative",
          targetExerciseId: "romanian-deadlift",
          strength: 0.55,
        },
      ],
    }),
    createExerciseDefinition({
      id: "leg-extension",
      name: "Leg Extension",
      movementPattern: "isolation",
      primaryMuscles: ["quads"],
      secondaryMuscles: [],
      equipment: ["machine"],
      difficulty: "beginner",
      skillScore: 1,
      category: "isolation",
      isCompound: false,
      pushPullLegs: "legs",
      fatigueScore: 3,
      jointStress: 4,
      axialLoading: false,
      tags: [
        "lower_body",
        "anterior_chain",
        "bilateral",
        "machine",
        "beginner_friendly",
        "low_axial",
        "accessory",
      ],
      relationships: [
        { kind: "alternative", targetExerciseId: "leg-press", strength: 0.45 },
      ],
    }),
    createExerciseDefinition({
      id: "dumbbell-row",
      name: "Dumbbell Row",
      movementPattern: "horizontal_pull",
      primaryMuscles: ["lats", "upper_back"],
      secondaryMuscles: ["biceps"],
      equipment: ["dumbbell"],
      difficulty: "beginner",
      skillScore: 3,
      pushPullLegs: "pull",
      isUnilateral: true,
      fatigueScore: 4,
      jointStress: 3,
      axialLoading: false,
      tags: [
        "row",
        "pull",
        "upper_body",
        "unilateral",
        "free_weight",
        "beginner_friendly",
        "low_axial",
      ],
      relationships: [
        {
          kind: "alternative",
          targetExerciseId: "chest-supported-row",
          strength: 0.8,
        },
        { kind: "alternative", targetExerciseId: "barbell-row", strength: 0.7 },
      ],
    }),
    createExerciseDefinition({
      id: "face-pull",
      name: "Face Pull",
      movementPattern: "horizontal_pull",
      primaryMuscles: ["shoulders", "upper_back"],
      secondaryMuscles: ["traps"],
      equipment: ["cable"],
      difficulty: "beginner",
      skillScore: 2,
      category: "isolation",
      isCompound: false,
      pushPullLegs: "pull",
      fatigueScore: 2,
      jointStress: 2,
      axialLoading: false,
      tags: [
        "pull",
        "upper_body",
        "bilateral",
        "machine",
        "beginner_friendly",
        "shoulder_friendly",
        "low_axial",
        "accessory",
      ],
      relationships: [],
    }),
  ]);

export function getIllustrativeCatalogSize(): number {
  return ILLUSTRATIVE_EXERCISE_CATALOG.length;
}
