import type { ExerciseAdjustment } from "./ExerciseAdjustment";
import type { ExerciseInsertion } from "./ExerciseInsertion";
import type { ExerciseRemoval } from "./ExerciseRemoval";
import type { ExerciseReplacement } from "./ExerciseReplacement";
import type { FatigueAdjustment } from "./FatigueAdjustment";
import type { FrequencyAdjustment } from "./FrequencyAdjustment";
import type { IntensityAdjustment } from "./IntensityAdjustment";
import type { LoadAdjustment } from "./LoadAdjustment";
import type { PlateauAdjustment } from "./PlateauAdjustment";
import type { ProgressionAdjustment } from "./ProgressionAdjustment";
import type { RecoveryAdjustment } from "./RecoveryAdjustment";
import type { RegressionAdjustment } from "./RegressionAdjustment";
import type { RepAdjustment } from "./RepAdjustment";
import type { RestAdjustment } from "./RestAdjustment";
import type { SessionAdjustment } from "./SessionAdjustment";
import type { SetAdjustment } from "./SetAdjustment";
import type { TempoAdjustment } from "./TempoAdjustment";
import type { VolumeAdjustment } from "./VolumeAdjustment";
import type { WeeklyAdjustment } from "./WeeklyAdjustment";
import type { WorkoutAdjustment } from "./WorkoutAdjustment";
import type { WorkoutMetadata } from "./WorkoutMetadata";
import type { WorkoutModification } from "./WorkoutModification";
import type { WorkoutReplacement } from "./WorkoutReplacement";

export interface WorkoutAdaptation {
  readonly id: string;
  readonly athleteId: string;
  readonly blueprintId: string;
  readonly contextId: string;
  readonly decisionKeys: readonly string[];
  readonly signalKeys: readonly string[];
  readonly modifications: readonly WorkoutModification[];
  readonly adjustments: readonly WorkoutAdjustment[];
  readonly replacements: readonly WorkoutReplacement[];
  readonly exerciseAdjustments: readonly ExerciseAdjustment[];
  readonly exerciseReplacements: readonly ExerciseReplacement[];
  readonly exerciseRemovals: readonly ExerciseRemoval[];
  readonly exerciseInsertions: readonly ExerciseInsertion[];
  readonly setAdjustments: readonly SetAdjustment[];
  readonly repAdjustments: readonly RepAdjustment[];
  readonly loadAdjustments: readonly LoadAdjustment[];
  readonly intensityAdjustments: readonly IntensityAdjustment[];
  readonly volumeAdjustments: readonly VolumeAdjustment[];
  readonly restAdjustments: readonly RestAdjustment[];
  readonly tempoAdjustments: readonly TempoAdjustment[];
  readonly frequencyAdjustments: readonly FrequencyAdjustment[];
  readonly weeklyAdjustments: readonly WeeklyAdjustment[];
  readonly progressionAdjustments: readonly ProgressionAdjustment[];
  readonly regressionAdjustments: readonly RegressionAdjustment[];
  readonly plateauAdjustments: readonly PlateauAdjustment[];
  readonly fatigueAdjustments: readonly FatigueAdjustment[];
  readonly recoveryAdjustments: readonly RecoveryAdjustment[];
  readonly sessionAdjustments: readonly SessionAdjustment[];
  readonly metadata: WorkoutMetadata;
  readonly createdAt: string;
}
