"""create exercise catalog tables

Revision ID: 55a562bc136f
Revises: 5ccce88c59dd
Create Date: 2026-07-11 22:50:22.566554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a562bc136f'
down_revision: Union[str, Sequence[str], None] = '5ccce88c59dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_equipment_slug'), 'equipment', ['slug'], unique=True)
    op.create_table('muscle_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_muscle_groups_slug'), 'muscle_groups', ['slug'], unique=True)
    op.create_table('exercises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.Enum('beginner', 'intermediate', 'advanced', name='difficulty_level_enum'), nullable=False),
    sa.Column('category', sa.Enum('compound', 'isolation', 'cardio', 'mobility', name='exercise_category_enum'), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_exercises_created_by_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_exercises_category'), 'exercises', ['category'], unique=False)
    op.create_index('ix_exercises_created_at', 'exercises', ['created_at'], unique=False)
    op.create_index(op.f('ix_exercises_created_by_id'), 'exercises', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_exercises_difficulty_level'), 'exercises', ['difficulty_level'], unique=False)
    op.create_index('ix_exercises_is_active', 'exercises', ['is_active'], unique=False)
    op.create_index(op.f('ix_exercises_slug'), 'exercises', ['slug'], unique=True)
    op.create_table('exercise_equipment',
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name='fk_exercise_equipment_equipment_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='fk_exercise_equipment_exercise_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'equipment_id')
    )
    op.create_index('ix_exercise_equipment_equipment_id', 'exercise_equipment', ['equipment_id'], unique=False)
    op.create_table('exercise_muscle_groups',
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('muscle_group_id', sa.Uuid(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='fk_exercise_muscle_groups_exercise_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_groups.id'], name='fk_exercise_muscle_groups_muscle_group_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_group_id')
    )
    op.create_index('ix_exercise_muscle_groups_muscle_group_id', 'exercise_muscle_groups', ['muscle_group_id'], unique=False)
    op.create_table('exercise_substitutions',
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('substitute_exercise_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Enum('equipment_alternative', 'injury_or_limitation', 'difficulty_progression', 'difficulty_regression', 'other', name='substitution_reason_enum'), nullable=True),
    sa.CheckConstraint('exercise_id != substitute_exercise_id', name='ck_exercise_substitutions_no_self_reference'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='fk_exercise_substitutions_exercise_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substitute_exercise_id'], ['exercises.id'], name='fk_exercise_substitutions_substitute_exercise_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'substitute_exercise_id')
    )
    op.create_index('ix_exercise_substitutions_substitute_exercise_id', 'exercise_substitutions', ['substitute_exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exercise_substitutions_substitute_exercise_id', table_name='exercise_substitutions')
    op.drop_table('exercise_substitutions')
    op.drop_index('ix_exercise_muscle_groups_muscle_group_id', table_name='exercise_muscle_groups')
    op.drop_table('exercise_muscle_groups')
    op.drop_index('ix_exercise_equipment_equipment_id', table_name='exercise_equipment')
    op.drop_table('exercise_equipment')
    op.drop_index(op.f('ix_exercises_slug'), table_name='exercises')
    op.drop_index('ix_exercises_is_active', table_name='exercises')
    op.drop_index(op.f('ix_exercises_difficulty_level'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_created_by_id'), table_name='exercises')
    op.drop_index('ix_exercises_created_at', table_name='exercises')
    op.drop_index(op.f('ix_exercises_category'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_muscle_groups_slug'), table_name='muscle_groups')
    op.drop_table('muscle_groups')
    op.drop_index(op.f('ix_equipment_slug'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
    # Dropping the tables above does not drop the enum types they used
    # (PostgreSQL enum types are independent objects); drop them explicitly
    # so downgrade() is a fully clean, reversible inverse of upgrade().
    op.execute("DROP TYPE IF EXISTS substitution_reason_enum")
    op.execute("DROP TYPE IF EXISTS exercise_category_enum")
    op.execute("DROP TYPE IF EXISTS difficulty_level_enum")
