"""create users table

Revision ID: 5ccce88c59dd
Revises: 
Create Date: 2026-07-09 22:38:07.637322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ccce88c59dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop enum types from any prior local run so they can be recreated
    # below with value-based labels (e.g. 'male') instead of name-based
    # labels (e.g. 'MALE'). Safe no-op on a clean database.
    op.execute("DROP TYPE IF EXISTS gender_enum")
    op.execute("DROP TYPE IF EXISTS activity_level_enum")
    op.execute("DROP TYPE IF EXISTS goal_enum")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'prefer_not_to_say', name='gender_enum'), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('current_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('activity_level', sa.Enum('sedentary', 'lightly_active', 'moderately_active', 'very_active', 'extremely_active', name='activity_level_enum'), nullable=True),
    sa.Column('goal', sa.Enum('lose_weight', 'maintain_weight', 'gain_muscle', 'improve_endurance', 'general_fitness', name='goal_enum'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('current_weight_kg IS NULL OR current_weight_kg > 0', name='ck_users_current_weight_kg_positive'),
    sa.CheckConstraint('height_cm IS NULL OR height_cm > 0', name='ck_users_height_cm_positive'),
    sa.CheckConstraint('target_weight_kg IS NULL OR target_weight_kg > 0', name='ck_users_target_weight_kg_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS gender_enum")
    op.execute("DROP TYPE IF EXISTS activity_level_enum")
    op.execute("DROP TYPE IF EXISTS goal_enum")
