"""create recovery check ins table

Revision ID: 699e9e7afa70
Revises: b92f14d464ca
Create Date: 2026-07-12 22:04:35.570963

Sprint 4.4 — Recovery Engine. Introduces ``RecoveryCheckIn``, a strictly
personal daily readiness journal entry (``NOT NULL user_id``, ``CASCADE``,
unlike ``Meal``'s catalog-vs-authored shape) with a unique
``(user_id, checkin_date)`` constraint enforcing exactly one check-in per
calendar day (see Decision 015 in ``docs/DECISIONS.md``). Deliberately
carries no training-load column — training load is derived at read time
from existing ``WorkoutLog``/``WorkoutSetLog`` history (see Decision 014).

Autogenerated with no hand-adjustment needed: unlike the meals/chat
migrations, this table introduces no native PostgreSQL enum type, so there
is no ``create_type``/``checkfirst`` subtlety to correct for.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699e9e7afa70'
down_revision: Union[str, Sequence[str], None] = 'b92f14d464ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('recovery_check_ins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('sleep_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=False),
    sa.Column('soreness', sa.Integer(), nullable=False),
    sa.Column('fatigue', sa.Integer(), nullable=False),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('hrv_ms', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('fatigue >= 1 AND fatigue <= 5', name='ck_recovery_check_ins_fatigue_range_valid'),
    sa.CheckConstraint('hrv_ms IS NULL OR hrv_ms > 0', name='ck_recovery_check_ins_hrv_ms_positive'),
    sa.CheckConstraint('resting_heart_rate IS NULL OR resting_heart_rate > 0', name='ck_recovery_check_ins_resting_heart_rate_positive'),
    sa.CheckConstraint('sleep_hours >= 0 AND sleep_hours <= 24', name='ck_recovery_check_ins_sleep_hours_range_valid'),
    sa.CheckConstraint('sleep_quality >= 1 AND sleep_quality <= 5', name='ck_recovery_check_ins_sleep_quality_range_valid'),
    sa.CheckConstraint('soreness >= 1 AND soreness <= 5', name='ck_recovery_check_ins_soreness_range_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_recovery_check_ins_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recovery_check_ins_user_id', 'recovery_check_ins', ['user_id'], unique=False)
    op.create_index('uq_recovery_check_ins_user_checkin_date', 'recovery_check_ins', ['user_id', 'checkin_date'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('uq_recovery_check_ins_user_checkin_date', table_name='recovery_check_ins')
    op.drop_index('ix_recovery_check_ins_user_id', table_name='recovery_check_ins')
    op.drop_table('recovery_check_ins')
