"""add workout log execution tables

Revision ID: a2567ea29561
Revises: da4e0b180322
Create Date: 2026-07-12 18:04:25.455454

Sprint 3.3 — Workout Execution. Autogenerated, then hand-adjusted:

- The autogenerated diff represented the ``performed_at`` -> ``completed_at``
  change as a drop + add, which would silently discard any already-logged
  completion timestamps. Replaced with ``alter_column(new_column_name=...)``
  so existing data survives.
- Autogenerate cannot detect a native enum value addition at all (it only
  diffs table/column structure), so the ``ALTER TYPE ... ADD VALUE`` for
  ``workout_log_status_enum`` was added by hand. It must run inside
  ``op.get_context().autocommit_block()`` because PostgreSQL cannot add an
  enum value inside the ambient transaction Alembic wraps each migration in
  (see ``env.py``'s ``context.begin_transaction()``), and the new label must
  be fully committed before ``uq_workout_logs_one_in_progress_per_user``'s
  partial predicate (``status = 'in_progress'``) can reference it.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2567ea29561'
down_revision: Union[str, Sequence[str], None] = 'da4e0b180322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Must run outside the ambient transaction and commit before anything
    # below references the new label (see module docstring).
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE workout_log_status_enum ADD VALUE IF NOT EXISTS 'in_progress' AFTER 'planned'")

    # Rename (not drop+add) so any already-logged completion timestamps
    # are preserved.
    op.alter_column('workout_logs', 'performed_at', new_column_name='completed_at')
    op.add_column('workout_logs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        'uq_workout_logs_one_in_progress_per_user',
        'workout_logs',
        ['user_id'],
        unique=True,
        postgresql_where=sa.text("status = 'in_progress'"),
    )

    op.create_table('workout_log_exercises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workout_log_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('workout_exercise_id', sa.Uuid(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('exercise_name_snapshot', sa.String(length=150), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps_min', sa.Integer(), nullable=True),
    sa.Column('target_reps_max', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rest_seconds IS NULL OR rest_seconds >= 0', name='ck_workout_log_exercises_rest_seconds_non_negative'),
    sa.CheckConstraint('target_reps_max IS NULL OR target_reps_max > 0', name='ck_workout_log_exercises_target_reps_max_positive'),
    sa.CheckConstraint('target_reps_min IS NULL OR target_reps_max IS NULL OR target_reps_max >= target_reps_min', name='ck_workout_log_exercises_target_reps_range_valid'),
    sa.CheckConstraint('target_reps_min IS NULL OR target_reps_min > 0', name='ck_workout_log_exercises_target_reps_min_positive'),
    sa.CheckConstraint('target_sets IS NULL OR target_sets > 0', name='ck_workout_log_exercises_target_sets_positive'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='fk_workout_log_exercises_exercise_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], name='fk_workout_log_exercises_workout_exercise_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workout_log_id'], ['workout_logs.id'], name='fk_workout_log_exercises_workout_log_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_log_exercises_exercise_id', 'workout_log_exercises', ['exercise_id'], unique=False)
    op.create_index('ix_workout_log_exercises_workout_log_id', 'workout_log_exercises', ['workout_log_id'], unique=False)
    op.create_index('uq_workout_log_exercises_log_order', 'workout_log_exercises', ['workout_log_id', 'order_index'], unique=True)

    op.create_table('workout_set_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workout_log_exercise_id', sa.Uuid(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds > 0', name='ck_workout_set_logs_duration_seconds_positive'),
    sa.CheckConstraint('reps IS NULL OR reps > 0', name='ck_workout_set_logs_reps_positive'),
    sa.CheckConstraint('rpe IS NULL OR (rpe >= 0 AND rpe <= 10)', name='ck_workout_set_logs_rpe_range_valid'),
    sa.CheckConstraint('set_number > 0', name='ck_workout_set_logs_set_number_positive'),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg > 0', name='ck_workout_set_logs_weight_kg_positive'),
    sa.ForeignKeyConstraint(['workout_log_exercise_id'], ['workout_log_exercises.id'], name='fk_workout_set_logs_workout_log_exercise_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_set_logs_workout_log_exercise_id', 'workout_set_logs', ['workout_log_exercise_id'], unique=False)
    op.create_index('uq_workout_set_logs_exercise_set_number', 'workout_set_logs', ['workout_log_exercise_id', 'set_number'], unique=True)


def downgrade() -> None:
    """Downgrade schema.

    PostgreSQL cannot drop a single enum value (``DROP TYPE ... ADD VALUE``
    has no inverse short of rebuilding the type), so ``'in_progress'``
    remains defined on ``workout_log_status_enum`` after downgrade — a
    harmless unused label, not a data integrity issue, since no row can
    reference it once the application code that produces it is gone.
    """
    op.drop_index('uq_workout_set_logs_exercise_set_number', table_name='workout_set_logs')
    op.drop_index('ix_workout_set_logs_workout_log_exercise_id', table_name='workout_set_logs')
    op.drop_table('workout_set_logs')

    op.drop_index('uq_workout_log_exercises_log_order', table_name='workout_log_exercises')
    op.drop_index('ix_workout_log_exercises_workout_log_id', table_name='workout_log_exercises')
    op.drop_index('ix_workout_log_exercises_exercise_id', table_name='workout_log_exercises')
    op.drop_table('workout_log_exercises')

    op.drop_index(
        'uq_workout_logs_one_in_progress_per_user',
        table_name='workout_logs',
        postgresql_where=sa.text("status = 'in_progress'"),
    )
    op.drop_column('workout_logs', 'started_at')
    op.alter_column('workout_logs', 'completed_at', new_column_name='performed_at')
