"""create goals and progress entries tables

Revision ID: a4facc05013e
Revises: 699e9e7afa70
Create Date: 2026-07-13 01:26:08.464413

Sprint 4.6 — Progress & Real LLM. Introduces ``Goal`` and ``Progress``
(``progress_entries`` table), both with the strictly personal ``NOT NULL``
``user_id``/``CASCADE`` ownership shape (matching ``RecoveryCheckIn``, not
``Meal``'s catalog-vs-authored shape — goals/progress are never shared).
Shipped together in one migration, with ``progress_entries.goal_id``
referencing ``goals.id``, since the two are introduced in the same sprint
with an immediate cross-reference — the cheapest point to get the
relationship right, per the precedent set by Decision 007 for
``Conversation``/``ChatMessage``.

Autogenerated, then hand-adjusted: ``progress_metric_type_enum`` is shared
by both tables (``goals.target_metric_type`` and
``progress_entries.metric_type``), so — matching the precedent set in
``b92f14d464ca_create_meals_and_meal_logs_tables.py`` for
``meal_type_enum`` — it is created/dropped explicitly with
``checkfirst=True`` via a ``postgresql.ENUM(..., create_type=False)``
instance rather than left to each ``create_table`` call's implicit enum
handling. The four single-use enums (``goal_type_enum``,
``goal_status_enum``, ``goal_priority_enum``, ``progress_source_enum``)
follow the simpler precedent from
``55a562bc136f_create_exercise_catalog_tables.py``: an explicit
``DROP TYPE IF EXISTS`` added to ``downgrade()``, since autogenerate never
emits one for a native enum introduced by ``create_table``.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a4facc05013e'
down_revision: Union[str, Sequence[str], None] = '699e9e7afa70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ``postgresql.ENUM`` (not the generic ``sa.Enum``) so ``create_type=False``
# is actually honored by both ``create_table`` calls below — the type is
# created/dropped explicitly instead (see module docstring).
progress_metric_type_enum = postgresql.ENUM(
    'body_weight', 'body_fat_percentage', 'lift_pr', 'run_time', 'circumference',
    name='progress_metric_type_enum',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    progress_metric_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_type', sa.Enum('strength_target', 'weight_target', 'habit', 'event_preparation', name='goal_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_metric_type', progress_metric_type_enum, nullable=True),
    sa.Column('target_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_unit', sa.String(length=20), nullable=True),
    sa.Column('target_exercise_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'achieved', 'abandoned', name='goal_status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='goal_priority_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('target_value IS NULL OR target_value >= 0', name='ck_goals_target_value_non_negative'),
    sa.ForeignKeyConstraint(['target_exercise_id'], ['exercises.id'], name='fk_goals_target_exercise_id_exercises', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_goals_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goals_user_id', 'goals', ['user_id'], unique=False)
    op.create_index('ix_goals_user_status', 'goals', ['user_id', 'status'], unique=False)
    op.create_table('progress_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('exercise_id', sa.Uuid(), nullable=True),
    sa.Column('metric_type', progress_metric_type_enum, nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'wearable', 'calculated', name='progress_source_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('value >= 0', name='ck_progress_entries_value_non_negative'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='fk_progress_entries_exercise_id_exercises', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name='fk_progress_entries_goal_id_goals', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_progress_entries_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_progress_entries_goal_id', 'progress_entries', ['goal_id'], unique=False)
    op.create_index(op.f('ix_progress_entries_metric_type'), 'progress_entries', ['metric_type'], unique=False)
    op.create_index('ix_progress_entries_user_id', 'progress_entries', ['user_id'], unique=False)
    op.create_index('ix_progress_entries_user_metric_date', 'progress_entries', ['user_id', 'metric_type', 'recorded_date'], unique=False)


def downgrade() -> None:
    """Downgrade schema.

    ``op.drop_table`` removes both tables but leaves the native enum types
    behind — dropped explicitly below (see module docstring).
    """
    op.drop_index('ix_progress_entries_user_metric_date', table_name='progress_entries')
    op.drop_index('ix_progress_entries_user_id', table_name='progress_entries')
    op.drop_index(op.f('ix_progress_entries_metric_type'), table_name='progress_entries')
    op.drop_index('ix_progress_entries_goal_id', table_name='progress_entries')
    op.drop_table('progress_entries')
    op.drop_index('ix_goals_user_status', table_name='goals')
    op.drop_index('ix_goals_user_id', table_name='goals')
    op.drop_table('goals')

    progress_metric_type_enum.drop(op.get_bind(), checkfirst=True)
    op.execute("DROP TYPE IF EXISTS progress_source_enum")
    op.execute("DROP TYPE IF EXISTS goal_priority_enum")
    op.execute("DROP TYPE IF EXISTS goal_status_enum")
    op.execute("DROP TYPE IF EXISTS goal_type_enum")
