"""create meals and meal logs tables

Revision ID: b92f14d464ca
Revises: bc3eb53f0581
Create Date: 2026-07-12 21:24:05.363445

Sprint 4.3 — Nutrition Engine. Introduces the ``Meal`` template (nullable
``created_by_id`` + ``is_public``, future-proofed for a shared/EVOLVE-provided
meal library — see Decision 012 in ``docs/DECISIONS.md``) alongside
``MealLog``, the strictly personal logged-diary-entry aggregate.

Autogenerated, then hand-adjusted: ``meal_type_enum`` is used by both tables,
so (matching the precedent set in ``bc3eb53f0581_create_conversations_and_
chat_messages_.py`` for ``chat_role_enum``) the type is created/dropped
explicitly with ``checkfirst=True`` rather than left to each ``create_table``
call's implicit (``checkfirst=False``) enum handling — verified by
round-tripping ``upgrade`` -> ``downgrade`` -> ``upgrade`` locally, which
fails with ``DuplicateObject: type "meal_type_enum" already exists`` on the
second ``upgrade`` without this change, since autogenerate never emits a
``DROP TYPE`` for a native enum introduced by ``create_table``.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b92f14d464ca'
down_revision: Union[str, Sequence[str], None] = 'bc3eb53f0581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ``postgresql.ENUM`` (not the generic ``sa.Enum``) so ``create_type=False``
# is actually honored by both ``create_table`` calls below — the type is
# created/dropped explicitly instead (see module docstring).
meal_type_enum = postgresql.ENUM(
    'breakfast', 'lunch', 'dinner', 'snack', 'pre_workout', 'post_workout', 'other',
    name='meal_type_enum',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    meal_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('meals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meal_type', meal_type_enum, nullable=False),
    sa.Column('calories', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('dietary_tags', sa.ARRAY(sa.String(length=30)), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('calories >= 0', name='ck_meals_calories_non_negative'),
    sa.CheckConstraint('carbs_g >= 0', name='ck_meals_carbs_g_non_negative'),
    sa.CheckConstraint('fat_g >= 0', name='ck_meals_fat_g_non_negative'),
    sa.CheckConstraint('protein_g >= 0', name='ck_meals_protein_g_non_negative'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_meals_created_by_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meals_created_by_id', 'meals', ['created_by_id'], unique=False)
    op.create_index('ix_meals_is_active', 'meals', ['is_active'], unique=False)
    op.create_index('ix_meals_is_public', 'meals', ['is_public'], unique=False)
    op.create_index(op.f('ix_meals_meal_type'), 'meals', ['meal_type'], unique=False)
    op.create_table('meal_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('meal_id', sa.Uuid(), nullable=True),
    sa.Column('name_snapshot', sa.String(length=150), nullable=False),
    sa.Column('meal_type', meal_type_enum, nullable=False),
    sa.Column('calories', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('calories >= 0', name='ck_meal_logs_calories_non_negative'),
    sa.CheckConstraint('carbs_g >= 0', name='ck_meal_logs_carbs_g_non_negative'),
    sa.CheckConstraint('fat_g >= 0', name='ck_meal_logs_fat_g_non_negative'),
    sa.CheckConstraint('protein_g >= 0', name='ck_meal_logs_protein_g_non_negative'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name='fk_meal_logs_meal_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_meal_logs_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meal_logs_meal_id', 'meal_logs', ['meal_id'], unique=False)
    op.create_index('ix_meal_logs_user_consumed', 'meal_logs', ['user_id', 'consumed_at'], unique=False)
    op.create_index('ix_meal_logs_user_id', 'meal_logs', ['user_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema.

    ``op.drop_table`` removes both tables but leaves the native
    ``meal_type_enum`` type behind — dropped explicitly below (see module
    docstring).
    """
    op.drop_index('ix_meal_logs_user_id', table_name='meal_logs')
    op.drop_index('ix_meal_logs_user_consumed', table_name='meal_logs')
    op.drop_index('ix_meal_logs_meal_id', table_name='meal_logs')
    op.drop_table('meal_logs')
    op.drop_index(op.f('ix_meals_meal_type'), table_name='meals')
    op.drop_index('ix_meals_is_public', table_name='meals')
    op.drop_index('ix_meals_is_active', table_name='meals')
    op.drop_index('ix_meals_created_by_id', table_name='meals')
    op.drop_table('meals')

    meal_type_enum.drop(op.get_bind(), checkfirst=True)
