"""create conversations and chat messages tables

Revision ID: bc3eb53f0581
Revises: 84b668dd4276
Create Date: 2026-07-12 19:29:59.247046

Sprint 4.2 — AI Orchestrator Infrastructure. Introduces the ``Conversation``
aggregate root alongside ``ChatMessage`` (rather than a bare
``conversation_id`` UUID column) — see Decision 007 in
``docs/DECISIONS.md`` for why the entity ships now, ahead of any feature
that consumes it (title, listing, archiving).

Autogenerated, then hand-adjusted: autogenerate never emits a
``DROP TYPE`` for a native enum introduced by ``create_table`` — verified
by round-tripping ``upgrade`` -> ``downgrade`` -> ``upgrade`` locally,
which failed on the second ``upgrade`` with
``DuplicateObject: type "chat_role_enum" already exists`` until the
explicit drop below was added.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc3eb53f0581'
down_revision: Union[str, Sequence[str], None] = '84b668dd4276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_conversations_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_user_id', 'conversations', ['user_id'], unique=False)
    op.create_index('ix_conversations_user_last_message', 'conversations', ['user_id', 'last_message_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='chat_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='fk_chat_messages_conversation_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_chat_messages_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_conversation_created', 'chat_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_chat_messages_user_id', 'chat_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    ``op.drop_table('chat_messages')`` removes the table but leaves the
    native ``chat_role_enum`` type behind — added by hand (see module
    docstring).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_user_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_conversation_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_conversations_user_last_message', table_name='conversations')
    op.drop_index('ix_conversations_user_id', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
    sa.Enum(name='chat_role_enum').drop(op.get_bind(), checkfirst=True)
