"""create program and workout tables

Revision ID: da4e0b180322
Revises: 55a562bc136f
Create Date: 2026-07-11 23:50:52.206487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'da4e0b180322'
down_revision: Union[str, Sequence[str], None] = '55a562bc136f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Enum('strength', 'hypertrophy', 'endurance', 'general_fitness', name='program_goal_enum'), nullable=False),
    # difficulty_level_enum already exists (created by migration 55a562bc136f for
    # exercises.difficulty_level) — create_type=False prevents a duplicate
    # CREATE TYPE here; this column reuses the existing PostgreSQL enum type.
    sa.Column('difficulty_level', postgresql.ENUM('beginner', 'intermediate', 'advanced', name='difficulty_level_enum', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='program_status_enum'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('duration_weeks > 0', name='ck_programs_duration_weeks_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_programs_created_by_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_programs_created_at', 'programs', ['created_at'], unique=False)
    op.create_index(op.f('ix_programs_created_by_id'), 'programs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_programs_difficulty_level'), 'programs', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_programs_goal'), 'programs', ['goal'], unique=False)
    op.create_index(op.f('ix_programs_slug'), 'programs', ['slug'], unique=True)
    op.create_index('ix_programs_status', 'programs', ['status'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('estimated_duration_minutes IS NULL OR estimated_duration_minutes > 0', name='ck_workouts_estimated_duration_minutes_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='fk_workouts_created_by_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workouts_created_at', 'workouts', ['created_at'], unique=False)
    op.create_index(op.f('ix_workouts_created_by_id'), 'workouts', ['created_by_id'], unique=False)
    op.create_index('ix_workouts_is_active', 'workouts', ['is_active'], unique=False)
    op.create_index(op.f('ix_workouts_slug'), 'workouts', ['slug'], unique=True)
    op.create_table('program_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='assignment_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name='fk_program_assignments_program_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_program_assignments_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_program_assignments_program_id', 'program_assignments', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_assignments_status'), 'program_assignments', ['status'], unique=False)
    op.create_index('ix_program_assignments_user_id', 'program_assignments', ['user_id'], unique=False)
    op.create_index('uq_program_assignments_one_active_per_user', 'program_assignments', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('program_days',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('workout_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_number > 0', name='ck_program_days_day_number_positive'),
    sa.CheckConstraint('week_number > 0', name='ck_program_days_week_number_positive'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name='fk_program_days_program_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='fk_program_days_workout_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_program_days_program_id_week_number', 'program_days', ['program_id', 'week_number'], unique=False)
    op.create_index(op.f('ix_program_days_workout_id'), 'program_days', ['workout_id'], unique=False)
    op.create_index('uq_program_days_program_week_day', 'program_days', ['program_id', 'week_number', 'day_number'], unique=True)
    op.create_table('workout_exercises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workout_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_reps_min', sa.Integer(), nullable=True),
    sa.Column('target_reps_max', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('rest_seconds IS NULL OR rest_seconds >= 0', name='ck_workout_exercises_rest_seconds_non_negative'),
    sa.CheckConstraint('target_reps_max IS NULL OR target_reps_max > 0', name='ck_workout_exercises_target_reps_max_positive'),
    sa.CheckConstraint('target_reps_min IS NULL OR target_reps_max IS NULL OR target_reps_max >= target_reps_min', name='ck_workout_exercises_target_reps_range_valid'),
    sa.CheckConstraint('target_reps_min IS NULL OR target_reps_min > 0', name='ck_workout_exercises_target_reps_min_positive'),
    sa.CheckConstraint('target_sets > 0', name='ck_workout_exercises_target_sets_positive'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='fk_workout_exercises_exercise_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='fk_workout_exercises_workout_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_exercises_exercise_id', 'workout_exercises', ['exercise_id'], unique=False)
    op.create_index('uq_workout_exercises_workout_order', 'workout_exercises', ['workout_id', 'order_index'], unique=True)
    op.create_table('workout_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('program_assignment_id', sa.Uuid(), nullable=True),
    sa.Column('workout_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'completed', 'skipped', name='workout_log_status_enum'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_actual_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('duration_actual_minutes IS NULL OR duration_actual_minutes > 0', name='ck_workout_logs_duration_actual_minutes_positive'),
    sa.ForeignKeyConstraint(['program_assignment_id'], ['program_assignments.id'], name='fk_workout_logs_program_assignment_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_workout_logs_user_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name='fk_workout_logs_workout_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_logs_program_assignment_id', 'workout_logs', ['program_assignment_id'], unique=False)
    op.create_index('ix_workout_logs_scheduled_date', 'workout_logs', ['scheduled_date'], unique=False)
    op.create_index('ix_workout_logs_status', 'workout_logs', ['status'], unique=False)
    op.create_index('ix_workout_logs_user_id', 'workout_logs', ['user_id'], unique=False)
    op.create_index('ix_workout_logs_workout_id', 'workout_logs', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workout_logs_workout_id', table_name='workout_logs')
    op.drop_index('ix_workout_logs_user_id', table_name='workout_logs')
    op.drop_index('ix_workout_logs_status', table_name='workout_logs')
    op.drop_index('ix_workout_logs_scheduled_date', table_name='workout_logs')
    op.drop_index('ix_workout_logs_program_assignment_id', table_name='workout_logs')
    op.drop_table('workout_logs')
    op.drop_index('uq_workout_exercises_workout_order', table_name='workout_exercises')
    op.drop_index('ix_workout_exercises_exercise_id', table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index('uq_program_days_program_week_day', table_name='program_days')
    op.drop_index(op.f('ix_program_days_workout_id'), table_name='program_days')
    op.drop_index('ix_program_days_program_id_week_number', table_name='program_days')
    op.drop_table('program_days')
    op.drop_index('uq_program_assignments_one_active_per_user', table_name='program_assignments', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_program_assignments_user_id', table_name='program_assignments')
    op.drop_index(op.f('ix_program_assignments_status'), table_name='program_assignments')
    op.drop_index('ix_program_assignments_program_id', table_name='program_assignments')
    op.drop_table('program_assignments')
    op.drop_index(op.f('ix_workouts_slug'), table_name='workouts')
    op.drop_index('ix_workouts_is_active', table_name='workouts')
    op.drop_index(op.f('ix_workouts_created_by_id'), table_name='workouts')
    op.drop_index('ix_workouts_created_at', table_name='workouts')
    op.drop_table('workouts')
    op.drop_index('ix_programs_status', table_name='programs')
    op.drop_index(op.f('ix_programs_slug'), table_name='programs')
    op.drop_index(op.f('ix_programs_goal'), table_name='programs')
    op.drop_index(op.f('ix_programs_difficulty_level'), table_name='programs')
    op.drop_index(op.f('ix_programs_created_by_id'), table_name='programs')
    op.drop_index('ix_programs_created_at', table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
    # Dropping the tables above does not drop the enum types they used
    # (PostgreSQL enum types are independent objects); drop them explicitly
    # so downgrade() is a fully clean, reversible inverse of upgrade().
    # difficulty_level_enum is NOT dropped here — it is owned by the
    # Sprint 3.1 migration and remains in use by the exercises table.
    op.execute("DROP TYPE IF EXISTS workout_log_status_enum")
    op.execute("DROP TYPE IF EXISTS assignment_status_enum")
    op.execute("DROP TYPE IF EXISTS program_status_enum")
    op.execute("DROP TYPE IF EXISTS program_goal_enum")
