import {
  CoachingSessionConfidenceLevels,
  type CoachingSessionConfidence,
  type CoachingSessionConfidenceLevel,
} from "../models/CoachingSessionConfidence";
import type { CoachingSessionEvidence } from "../models/CoachingSessionEvidence";

/**
 * Deterministic confidence from available evidence only.
 * Never generated by an LLM.
 *
 * score: clamp(evidenceCount * 0.15 + sourceCount * 0.1, 0, 1)
 * level: none=0, low<0.4, medium<0.75, high>=0.75
 */
export function calculateSessionConfidence(
  evidence: CoachingSessionEvidence,
): CoachingSessionConfidence {
  const evidenceCount = evidence.items.length;
  const sourceCount = evidence.sources.length;
  const raw = evidenceCount * 0.15 + sourceCount * 0.1;
  const score = Math.max(0, Math.min(1, Math.round(raw * 100) / 100));

  let level: CoachingSessionConfidenceLevel =
    CoachingSessionConfidenceLevels.NONE;
  if (evidenceCount === 0) {
    level = CoachingSessionConfidenceLevels.NONE;
  } else if (score < 0.4) {
    level = CoachingSessionConfidenceLevels.LOW;
  } else if (score < 0.75) {
    level = CoachingSessionConfidenceLevels.MEDIUM;
  } else {
    level = CoachingSessionConfidenceLevels.HIGH;
  }

  return Object.freeze({
    level,
    score,
    evidenceCount,
    sourceCount,
    rationale: `Deterministic confidence from ${evidenceCount} evidence item(s) across ${sourceCount} source(s).`,
  });
}
