"""Pydantic schemas package — API request/response contracts."""

from app.schemas.auth import LoginRequest, RefreshRequest, TokenResponse
from app.schemas.catalog import (
    EquipmentCreate,
    EquipmentRead,
    MuscleGroupCreate,
    MuscleGroupRead,
)
from app.schemas.exercise import (
    EquipmentWithRole,
    ExerciseCreate,
    ExerciseEquipmentInput,
    ExerciseMuscleGroupInput,
    ExercisePage,
    ExercisePublic,
    ExerciseSubstitutionCreate,
    ExerciseSubstitutionRead,
    ExerciseSummary,
    ExerciseUpdate,
    MuscleGroupWithRole,
)
from app.schemas.program import (
    ProgramAssignmentRead,
    ProgramCreate,
    ProgramDayInput,
    ProgramDayRead,
    ProgramPage,
    ProgramPublic,
    ProgramUpdate,
)
from app.schemas.user import UserCreate, UserPublic, UserRead, UserUpdate
from app.schemas.workout import (
    WorkoutCreate,
    WorkoutExerciseInput,
    WorkoutExerciseRead,
    WorkoutPage,
    WorkoutPublic,
    WorkoutUpdate,
)
from app.schemas.workout_log import (
    WorkoutLogDetail,
    WorkoutLogExerciseCreate,
    WorkoutLogExerciseRead,
    WorkoutLogFinish,
    WorkoutLogPage,
    WorkoutLogStart,
    WorkoutLogSummary,
    WorkoutSetLogCreate,
    WorkoutSetLogRead,
    WorkoutSetLogUpdate,
)

__all__ = [
    "EquipmentCreate",
    "EquipmentRead",
    "EquipmentWithRole",
    "ExerciseCreate",
    "ExerciseEquipmentInput",
    "ExerciseMuscleGroupInput",
    "ExercisePage",
    "ExercisePublic",
    "ExerciseSubstitutionCreate",
    "ExerciseSubstitutionRead",
    "ExerciseSummary",
    "ExerciseUpdate",
    "LoginRequest",
    "MuscleGroupCreate",
    "MuscleGroupRead",
    "MuscleGroupWithRole",
    "ProgramAssignmentRead",
    "ProgramCreate",
    "ProgramDayInput",
    "ProgramDayRead",
    "ProgramPage",
    "ProgramPublic",
    "ProgramUpdate",
    "RefreshRequest",
    "TokenResponse",
    "UserCreate",
    "UserPublic",
    "UserRead",
    "UserUpdate",
    "WorkoutCreate",
    "WorkoutExerciseInput",
    "WorkoutExerciseRead",
    "WorkoutLogDetail",
    "WorkoutLogExerciseCreate",
    "WorkoutLogExerciseRead",
    "WorkoutLogFinish",
    "WorkoutLogPage",
    "WorkoutLogStart",
    "WorkoutLogSummary",
    "WorkoutPage",
    "WorkoutPublic",
    "WorkoutSetLogCreate",
    "WorkoutSetLogRead",
    "WorkoutSetLogUpdate",
    "WorkoutUpdate",
]
