"""Pydantic v2 schemas for the Exercise domain — request/response contracts.

These schemas define the API surface independently of the SQLAlchemy
``Exercise``/``ExerciseMuscleGroup``/``ExerciseEquipment``/
``ExerciseSubstitution`` models (see ``app.models.exercise``). ``slug`` is
never client-supplied — it is always generated by
:class:`~app.services.exercise_service.ExerciseService`.
"""

import uuid
from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, HttpUrl, StringConstraints, model_validator

from app.models.exercise import (
    DifficultyLevel,
    Exercise,
    ExerciseCategory,
    ExerciseEquipment,
    ExerciseMuscleGroup,
    ExerciseSubstitution,
    SubstitutionReason,
)
from app.schemas.catalog import EquipmentRead, MuscleGroupRead

ExerciseNameField = Annotated[str, StringConstraints(min_length=2, max_length=150)]
ExerciseTextField = Annotated[str, StringConstraints(max_length=10_000)]


class ExerciseMuscleGroupInput(BaseModel):
    """A single muscle-group association supplied when creating/updating an exercise."""

    muscle_group_id: uuid.UUID
    is_primary: bool = False


class ExerciseEquipmentInput(BaseModel):
    """A single equipment association supplied when creating/updating an exercise."""

    equipment_id: uuid.UUID
    is_required: bool = True


def _check_exactly_one_primary_muscle_group(
    muscle_groups: list[ExerciseMuscleGroupInput],
) -> list[ExerciseMuscleGroupInput]:
    """Ensure a non-empty list of muscle groups has exactly one primary entry."""
    if len(muscle_groups) == 0:
        raise ValueError("at least one muscle group is required")
    primary_count = sum(1 for entry in muscle_groups if entry.is_primary)
    if primary_count != 1:
        raise ValueError("exactly one muscle group must be marked as primary")
    return muscle_groups


class ExerciseCreate(BaseModel):
    """Input schema for adding a new exercise to the catalog."""

    name: ExerciseNameField
    description: ExerciseTextField | None = None
    instructions: ExerciseTextField | None = None
    difficulty_level: DifficultyLevel
    category: ExerciseCategory
    video_url: HttpUrl | None = None
    image_url: HttpUrl | None = None
    muscle_groups: list[ExerciseMuscleGroupInput]
    equipment: list[ExerciseEquipmentInput] = []

    @model_validator(mode="after")
    def _check_muscle_groups(self) -> "ExerciseCreate":
        _check_exactly_one_primary_muscle_group(self.muscle_groups)
        return self


class ExerciseUpdate(BaseModel):
    """Input schema for partially updating an existing exercise.

    All fields are optional so clients submit only the attributes they wish
    to change. ``muscle_groups``/``equipment``, when provided, replace the
    full association set (see ``ExerciseRepository.replace_muscle_groups``).
    """

    name: ExerciseNameField | None = None
    description: ExerciseTextField | None = None
    instructions: ExerciseTextField | None = None
    difficulty_level: DifficultyLevel | None = None
    category: ExerciseCategory | None = None
    video_url: HttpUrl | None = None
    image_url: HttpUrl | None = None
    is_active: bool | None = None
    muscle_groups: list[ExerciseMuscleGroupInput] | None = None
    equipment: list[ExerciseEquipmentInput] | None = None

    @model_validator(mode="after")
    def _check_muscle_groups(self) -> "ExerciseUpdate":
        if self.muscle_groups is not None:
            _check_exactly_one_primary_muscle_group(self.muscle_groups)
        return self


class MuscleGroupWithRole(MuscleGroupRead):
    """A :class:`MuscleGroupRead` plus its role on a specific exercise."""

    is_primary: bool

    @classmethod
    def from_link(cls, link: ExerciseMuscleGroup) -> "MuscleGroupWithRole":
        """Build this schema from a loaded :class:`ExerciseMuscleGroup` association."""
        return cls(
            id=link.muscle_group.id,
            name=link.muscle_group.name,
            slug=link.muscle_group.slug,
            description=link.muscle_group.description,
            created_at=link.muscle_group.created_at,
            updated_at=link.muscle_group.updated_at,
            is_primary=link.is_primary,
        )


class EquipmentWithRole(EquipmentRead):
    """An :class:`EquipmentRead` plus its role on a specific exercise."""

    is_required: bool

    @classmethod
    def from_link(cls, link: ExerciseEquipment) -> "EquipmentWithRole":
        """Build this schema from a loaded :class:`ExerciseEquipment` association."""
        return cls(
            id=link.equipment.id,
            name=link.equipment.name,
            slug=link.equipment.slug,
            description=link.equipment.description,
            created_at=link.equipment.created_at,
            updated_at=link.equipment.updated_at,
            is_required=link.is_required,
        )


class ExercisePublic(BaseModel):
    """Public-facing representation of an exercise, with resolved associations."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    name: str
    slug: str
    description: str | None
    instructions: str | None
    difficulty_level: DifficultyLevel
    category: ExerciseCategory
    video_url: str | None
    image_url: str | None
    is_active: bool
    muscle_groups: list[MuscleGroupWithRole]
    equipment: list[EquipmentWithRole]
    created_at: datetime
    updated_at: datetime

    @classmethod
    def from_model(cls, exercise: Exercise) -> "ExercisePublic":
        """Build this schema from an :class:`Exercise` with associations loaded."""
        return cls(
            id=exercise.id,
            name=exercise.name,
            slug=exercise.slug,
            description=exercise.description,
            instructions=exercise.instructions,
            difficulty_level=exercise.difficulty_level,
            category=exercise.category,
            video_url=exercise.video_url,
            image_url=exercise.image_url,
            is_active=exercise.is_active,
            muscle_groups=[
                MuscleGroupWithRole.from_link(link) for link in exercise.muscle_group_links
            ],
            equipment=[EquipmentWithRole.from_link(link) for link in exercise.equipment_links],
            created_at=exercise.created_at,
            updated_at=exercise.updated_at,
        )


class ExercisePage(BaseModel):
    """A paginated page of :class:`ExercisePublic` results."""

    items: list[ExercisePublic]
    total: int
    limit: int
    offset: int


class ExerciseSummary(BaseModel):
    """A minimal exercise representation, used inside substitution results."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    name: str
    slug: str
    difficulty_level: DifficultyLevel
    category: ExerciseCategory


class ExerciseSubstitutionCreate(BaseModel):
    """Input schema for registering a substitution edge for an exercise."""

    substitute_exercise_id: uuid.UUID
    reason: SubstitutionReason | None = None


class ExerciseSubstitutionRead(BaseModel):
    """Public-facing representation of a single substitution edge."""

    substitute: ExerciseSummary
    reason: SubstitutionReason | None

    @classmethod
    def from_link(cls, link: ExerciseSubstitution) -> "ExerciseSubstitutionRead":
        """Build this schema from a loaded :class:`ExerciseSubstitution` association."""
        return cls(
            substitute=ExerciseSummary.model_validate(link.substitute_exercise),
            reason=link.reason,
        )
