"""Pydantic v2 schemas for the Program domain — request/response contracts.

These schemas define the API surface independently of the SQLAlchemy
``Program``/``ProgramDay``/``ProgramAssignment`` models (see
``app.models.program``). ``slug`` is never client-supplied — it is always
generated by :class:`~app.services.workout_service.WorkoutService`, mirroring
``ExerciseService``. ``status``/``AssignmentStatus`` transitions are likewise
never accepted as free-form input; they are only ever set by dedicated
service methods (e.g. publish/archive, assign/complete/abandon).
"""

import uuid
from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, StringConstraints

from app.models.exercise import DifficultyLevel
from app.models.program import AssignmentStatus, ProgramGoal, ProgramStatus

ProgramNameField = Annotated[str, StringConstraints(min_length=2, max_length=150)]
ProgramTextField = Annotated[str, StringConstraints(max_length=10_000)]
ProgramDayLabelField = Annotated[str, StringConstraints(min_length=1, max_length=150)]


class ProgramCreate(BaseModel):
    """Input schema for authoring a new program template.

    New programs always start in :attr:`ProgramStatus.DRAFT` — ``status``
    is intentionally absent here; publishing is a dedicated service
    transition (mirrors ``ExerciseService.deactivate_exercise`` guarding
    ``is_active`` behind a method rather than free-form update).
    """

    name: ProgramNameField
    description: ProgramTextField | None = None
    duration_weeks: int
    goal: ProgramGoal
    difficulty_level: DifficultyLevel


class ProgramUpdate(BaseModel):
    """Input schema for partially updating an existing program template.

    All fields are optional so clients submit only the attributes they
    wish to change. Excludes ``status`` for the same reason as
    :class:`ProgramCreate`.
    """

    name: ProgramNameField | None = None
    description: ProgramTextField | None = None
    duration_weeks: int | None = None
    goal: ProgramGoal | None = None
    difficulty_level: DifficultyLevel | None = None


class ProgramDayInput(BaseModel):
    """Input schema for scheduling a day within a program.

    ``day_number`` is scoped within ``week_number`` — it is never a global
    sequence across the whole program (see ``app.models.program.ProgramDay``).
    A ``workout_id`` of ``None`` represents a rest day.
    """

    week_number: int
    day_number: int
    label: ProgramDayLabelField | None = None
    workout_id: uuid.UUID | None = None


class ProgramDayRead(BaseModel):
    """Public-facing representation of a single scheduled program day."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    program_id: uuid.UUID
    week_number: int
    day_number: int
    label: str | None
    workout_id: uuid.UUID | None
    created_at: datetime
    updated_at: datetime


class ProgramPublic(BaseModel):
    """Public-facing representation of a program template."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    name: str
    slug: str
    description: str | None
    duration_weeks: int
    goal: ProgramGoal
    difficulty_level: DifficultyLevel
    status: ProgramStatus
    created_at: datetime
    updated_at: datetime


class ProgramPage(BaseModel):
    """A paginated page of :class:`ProgramPublic` results."""

    items: list[ProgramPublic]
    total: int
    limit: int
    offset: int


class ProgramAssignmentRead(BaseModel):
    """Public-facing representation of a user's assignment to a program."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    program_id: uuid.UUID
    user_id: uuid.UUID
    status: AssignmentStatus
    started_at: datetime
    ended_at: datetime | None
    created_at: datetime
    updated_at: datetime
