"""Pydantic v2 schemas for the Workout *template* domain — request/response contracts.

These schemas define the API surface independently of the SQLAlchemy
``Workout``/``WorkoutExercise`` models (see ``app.models.workout``).
``slug`` is never client-supplied — it is always generated by
:class:`~app.services.workout_service.WorkoutService`, mirroring
``ExerciseService``.

Logged-session schemas (``WorkoutLogStart``, ``WorkoutLogDetail``, etc.)
live in ``app.schemas.workout_log`` — a separate contract for the
*execution* aggregate, per the Sprint 3.3 design.
"""

import uuid
from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, StringConstraints, model_validator

from app.models.workout import Workout

WorkoutNameField = Annotated[str, StringConstraints(min_length=2, max_length=150)]
WorkoutTextField = Annotated[str, StringConstraints(max_length=10_000)]


class WorkoutExerciseInput(BaseModel):
    """A single ordered exercise line item supplied when creating/updating a workout."""

    exercise_id: uuid.UUID
    order_index: int
    target_sets: int
    target_reps_min: int | None = None
    target_reps_max: int | None = None
    rest_seconds: int | None = None
    notes: WorkoutTextField | None = None

    @model_validator(mode="after")
    def _check_rep_range(self) -> "WorkoutExerciseInput":
        """Ensure ``target_reps_max`` is not below ``target_reps_min`` when both are given."""
        if (
            self.target_reps_min is not None
            and self.target_reps_max is not None
            and self.target_reps_max < self.target_reps_min
        ):
            raise ValueError("target_reps_max must be >= target_reps_min")
        return self


class WorkoutCreate(BaseModel):
    """Input schema for authoring a new workout template."""

    name: WorkoutNameField
    description: WorkoutTextField | None = None
    estimated_duration_minutes: int | None = None
    exercises: list[WorkoutExerciseInput]

    @model_validator(mode="after")
    def _check_unique_order_indexes(self) -> "WorkoutCreate":
        """Ensure no two exercise line items share the same ``order_index``."""
        order_indexes = [entry.order_index for entry in self.exercises]
        if len(order_indexes) != len(set(order_indexes)):
            raise ValueError("exercises must have unique order_index values")
        return self


class WorkoutUpdate(BaseModel):
    """Input schema for partially updating an existing workout template.

    All fields are optional so clients submit only the attributes they
    wish to change. ``exercises``, when provided, replaces the full line
    item set (see ``WorkoutRepository.replace_exercises``).
    """

    name: WorkoutNameField | None = None
    description: WorkoutTextField | None = None
    estimated_duration_minutes: int | None = None
    is_active: bool | None = None
    exercises: list[WorkoutExerciseInput] | None = None

    @model_validator(mode="after")
    def _check_unique_order_indexes(self) -> "WorkoutUpdate":
        """Ensure no two exercise line items share the same ``order_index``, if provided."""
        if self.exercises is not None:
            order_indexes = [entry.order_index for entry in self.exercises]
            if len(order_indexes) != len(set(order_indexes)):
                raise ValueError("exercises must have unique order_index values")
        return self


class WorkoutExerciseRead(BaseModel):
    """Public-facing representation of a single ordered exercise line item."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    exercise_id: uuid.UUID
    order_index: int
    target_sets: int
    target_reps_min: int | None
    target_reps_max: int | None
    rest_seconds: int | None
    notes: str | None


class WorkoutPublic(BaseModel):
    """Public-facing representation of a workout template, with ordered exercises."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    name: str
    slug: str
    description: str | None
    estimated_duration_minutes: int | None
    is_active: bool
    exercises: list[WorkoutExerciseRead]
    created_at: datetime
    updated_at: datetime

    @classmethod
    def from_model(cls, workout: Workout) -> "WorkoutPublic":
        """Build this schema from a :class:`Workout` with ``exercise_links`` loaded.

        The model's relationship is named ``exercise_links`` (see
        ``app.models.workout``); this maps it onto the schema's public
        ``exercises`` field, mirroring ``ExercisePublic.from_model``.
        """
        return cls(
            id=workout.id,
            name=workout.name,
            slug=workout.slug,
            description=workout.description,
            estimated_duration_minutes=workout.estimated_duration_minutes,
            is_active=workout.is_active,
            exercises=[
                WorkoutExerciseRead.model_validate(link) for link in workout.exercise_links
            ],
            created_at=workout.created_at,
            updated_at=workout.updated_at,
        )


class WorkoutPage(BaseModel):
    """A paginated page of :class:`WorkoutPublic` results."""

    items: list[WorkoutPublic]
    total: int
    limit: int
    offset: int
