import type { CalorieAdjustment } from "./CalorieAdjustment";
import type { CarbohydrateAdjustment } from "./CarbohydrateAdjustment";
import type { DietBreakAdjustment } from "./DietBreakAdjustment";
import type { FatAdjustment } from "./FatAdjustment";
import type { FiberAdjustment } from "./FiberAdjustment";
import type { HydrationAdjustment } from "./HydrationAdjustment";
import type { MacroDistributionAdjustment } from "./MacroDistributionAdjustment";
import type { MealAdjustment } from "./MealAdjustment";
import type { MealInsertion } from "./MealInsertion";
import type { MealRemoval } from "./MealRemoval";
import type { MealReplacement } from "./MealReplacement";
import type { MealTimingAdjustment } from "./MealTimingAdjustment";
import type { NutritionAdjustment } from "./NutritionAdjustment";
import type { NutritionMetadata } from "./NutritionMetadata";
import type { NutritionModification } from "./NutritionModification";
import type { NutritionReplacement } from "./NutritionReplacement";
import type { ProteinAdjustment } from "./ProteinAdjustment";
import type { RefeedAdjustment } from "./RefeedAdjustment";
import type { SupplementAdjustment } from "./SupplementAdjustment";
import type { WeeklyAdjustment } from "./WeeklyAdjustment";

export interface NutritionAdaptation {
  readonly id: string;
  readonly athleteId: string;
  readonly planId: string;
  readonly contextId: string;
  readonly decisionKeys: readonly string[];
  readonly signalKeys: readonly string[];
  readonly modifications: readonly NutritionModification[];
  readonly adjustments: readonly NutritionAdjustment[];
  readonly replacements: readonly NutritionReplacement[];
  readonly mealAdjustments: readonly MealAdjustment[];
  readonly mealReplacements: readonly MealReplacement[];
  readonly mealRemovals: readonly MealRemoval[];
  readonly mealInsertions: readonly MealInsertion[];
  readonly calorieAdjustments: readonly CalorieAdjustment[];
  readonly proteinAdjustments: readonly ProteinAdjustment[];
  readonly carbohydrateAdjustments: readonly CarbohydrateAdjustment[];
  readonly fatAdjustments: readonly FatAdjustment[];
  readonly fiberAdjustments: readonly FiberAdjustment[];
  readonly hydrationAdjustments: readonly HydrationAdjustment[];
  readonly mealTimingAdjustments: readonly MealTimingAdjustment[];
  readonly supplementAdjustments: readonly SupplementAdjustment[];
  readonly refeedAdjustments: readonly RefeedAdjustment[];
  readonly dietBreakAdjustments: readonly DietBreakAdjustment[];
  readonly macroDistributionAdjustments: readonly MacroDistributionAdjustment[];
  readonly weeklyAdjustments: readonly WeeklyAdjustment[];
  readonly metadata: NutritionMetadata;
  readonly createdAt: string;
}
