import type { Exercise } from "../models/Exercise";
import type { ExerciseMetadata } from "../models/ExerciseMetadata";
import type { ExerciseMuscleGroup } from "../models/ExerciseMuscleGroup";
import { createDefaultExerciseMetadata } from "../models/ExerciseMetadata";
import type { ExerciseKnowledge } from "../models/ExerciseKnowledge";
import { createDefaultExerciseKnowledge } from "../models/ExerciseKnowledge";

interface ExerciseEnrichment {
  metadata?: Partial<ExerciseMetadata>;
  primaryMuscles?: ExerciseMuscleGroup[];
  secondaryMuscles?: ExerciseMuscleGroup[];
  stabilizerMuscles?: ExerciseMuscleGroup[];
  commonMistakes?: string[];
  knowledge?: Partial<ExerciseKnowledge>;
}

/** Static enrichment for mock catalog exercises until catalog metadata is fully wired. */
const EXERCISE_ENRICHMENT: Record<string, ExerciseEnrichment> = {
  "ex-low-bar-squat": {
    metadata: {
      difficulty: "Advanced",
      movementPattern: "squat",
      equipment: ["barbell"],
      unilateral: false,
      bodyRegion: "lower-body",
      tempo: "3-1-1",
      recommendedRestSeconds: 180,
      coachTip: "Brace your torso and keep the bar path over mid-foot.",
      executionSteps: [
        "Set the bar across the upper back and position your feet shoulder-width apart.",
        "Descend until your hips break below parallel with a neutral spine.",
        "Drive through the floor and stand tall without bouncing.",
      ],
      breathingInstructions: "Inhale at the top, brace, and exhale forcefully as you stand.",
      rangeOfMotion: "Full squat depth with a strong upright torso.",
      safetyNotes: ["Keep the knees tracking over the toes.", "Do not lose tension in the upper back."],
    },
    knowledge: {
      aliases: ["low-bar back squat"],
      substitutions: [{ id: "ex-high-bar-squat", reason: "similar squat pattern" }, { id: "ex-front-squat" }],
      variations: [{ id: "ex-box-squat" }],
      tags: ["strength", "compound"],
    },
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    stabilizerMuscles: ["core"],
    commonMistakes: [
      "Knees caving inward on the ascent",
      "Losing upper-back tightness",
      "Bouncing out of the hole",
    ],
  },
  "ex-bench-press": {
    metadata: {
      difficulty: "Intermediate",
      movementPattern: "push",
      equipment: ["barbell"],
      unilateral: false,
      bodyRegion: "upper-body",
      tempo: "2-1-1",
      recommendedRestSeconds: 150,
      coachTip: "Keep the shoulder blades tucked and the wrists stacked over the elbows.",
      executionSteps: [
        "Plant your feet and create a stable base before unracking the bar.",
        "Lower the bar to the midline of the chest while keeping elbows at roughly 45°.",
        "Drive the bar back up without arching excessively.",
      ],
      breathingInstructions: "Take a deep breath into the ribs before the descent and exhale at the top.",
      rangeOfMotion: "Touch the chest lightly and lock out without flaring the elbows.",
      safetyNotes: ["Use a spotter for heavy loads.", "Keep the wrists neutral."],
    },
    knowledge: {
      substitutions: [{ id: "ex-incline-db-press", reason: "upper-chest emphasis" }],
      tags: ["press"],
    },
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    stabilizerMuscles: ["core"],
    commonMistakes: [
      "Flaring elbows too wide",
      "Losing shoulder-blade retraction",
      "Bouncing the bar off the chest",
    ],
  },
  "ex-deadlift": {
    metadata: {
      difficulty: "Advanced",
      movementPattern: "hinge",
      equipment: ["barbell"],
      unilateral: false,
      bodyRegion: "posterior-chain",
      tempo: "1-0-1",
      recommendedRestSeconds: 180,
      coachTip: "Keep the bar close and allow the hips and shoulders to rise together.",
      executionSteps: [
        "Set the feet under the bar and brace the trunk before pulling.",
        "Extend through the floor until the torso is upright.",
        "Lower the load under control without rounding the back.",
      ],
      breathingInstructions: "Brace before the first pull and maintain tension through the set.",
      rangeOfMotion: "Full floor-to-standing range with controlled lowering.",
      safetyNotes: ["Keep the spine neutral.", "Avoid overloading if form is compromised."],
    },
    knowledge: {
      substitutions: [{ id: "ex-romanian-deadlift", reason: "hamstring focus" }],
      tags: ["hinge", "posterior-chain"],
    },
    primaryMuscles: ["back", "hamstrings"],
    secondaryMuscles: ["glutes", "core"],
    stabilizerMuscles: ["core", "glutes"],
    commonMistakes: [
      "Rounding the lower back",
      "Jerking the bar off the floor",
      "Hips shooting up before the chest",
    ],
  },
  "ex-overhead-press": {
    metadata: {
      difficulty: "Intermediate",
      movementPattern: "push",
      equipment: ["barbell"],
      unilateral: false,
      bodyRegion: "upper-body",
      tempo: "2-1-2",
      recommendedRestSeconds: 120,
      coachTip: "Ribcage down and glutes tight help keep the press vertical.",
      executionSteps: [
        "Start with the bar at upper chest level and feet under the hips.",
        "Press the bar up without letting the lower back take over.",
        "Lock the elbows out and pause briefly overhead.",
      ],
      breathingInstructions: "Inhale before pressing and exhale once the bar passes the forehead.",
      rangeOfMotion: "Full overhead lockout with a stable trunk.",
      safetyNotes: ["Avoid excessive arching.", "Keep the bar path over the mid-foot."],
    },
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "core"],
    stabilizerMuscles: ["core"],
    commonMistakes: [
      "Excessive lower-back arch",
      "Pressing the bar forward instead of up",
      "Incomplete lockout overhead",
    ],
  },
  "ex-chest-supported-row": {
    metadata: {
      difficulty: "Beginner",
      movementPattern: "pull",
      equipment: ["machine"],
      unilateral: false,
      bodyRegion: "upper-back",
      tempo: "2-1-2",
      recommendedRestSeconds: 90,
      coachTip: "Pull the elbows toward the ribs and avoid shrugging the shoulders.",
      executionSteps: [
        "Set your chest firmly on the pad and grip the handles.",
        "Draw the elbows back without letting the torso swing.",
        "Control the return to the start position.",
      ],
      breathingInstructions: "Exhale as you row and inhale on the return.",
      rangeOfMotion: "Full shoulder extension with a controlled return.",
      safetyNotes: ["Keep the chest supported throughout the set."],
    },
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps"],
    stabilizerMuscles: ["core"],
    commonMistakes: ["Pulling the handles too high", "Using momentum to swing the torso"],
  },
  "ex-leg-curl": {
    metadata: {
      difficulty: "Beginner",
      movementPattern: "hinge",
      equipment: ["machine"],
      unilateral: false,
      bodyRegion: "posterior-chain",
      tempo: "2-1-2",
      recommendedRestSeconds: 60,
      coachTip: "Keep the hips pinned to the pad and control the eccentric.",
      executionSteps: ["Curl the pad toward the glutes", "Pause briefly at full contraction", "Lower slowly to full extension"],
      breathingInstructions: "Exhale as you curl and inhale on the way down.",
      rangeOfMotion: "Full hamstring flexion without hip extension.",
      safetyNotes: ["Do not overextend the knees at the bottom."],
    },
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["calves"],
    stabilizerMuscles: ["core"],
    commonMistakes: ["Rolling out of the pad", "Using momentum to finish the rep"],
  },
  "ex-dumbbell-curl": {
    metadata: {
      difficulty: "Beginner",
      movementPattern: "pull",
      equipment: ["dumbbell"],
      unilateral: false,
      bodyRegion: "upper-arm",
      tempo: "2-1-2",
      recommendedRestSeconds: 60,
      coachTip: "Keep the elbows fixed and avoid swinging the dumbbells.",
      executionSteps: ["Hold the dumbbells at the sides", "Curl without shifting the torso", "Lower under control"],
      breathingInstructions: "Exhale while curling and inhale on the return.",
      rangeOfMotion: "Full elbow flexion to full extension.",
      safetyNotes: ["Avoid using momentum to cheat the reps."],
    },
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["triceps"],
    stabilizerMuscles: ["core"],
    commonMistakes: ["Swinging the torso", "Letting the elbows drift forward"],
  },
  "ex-pull-up": {
    metadata: {
      difficulty: "Intermediate",
      movementPattern: "pull",
      equipment: ["bodyweight"],
      unilateral: false,
      bodyRegion: "upper-back",
      tempo: "2-1-2",
      recommendedRestSeconds: 120,
      coachTip: "Start from a dead hang and pull the elbows toward the ribs.",
      executionSteps: ["Hang from the bar with shoulders active", "Pull until the chin passes the bar", "Lower under control"],
      breathingInstructions: "Exhale as you pull and inhale on the descent.",
      rangeOfMotion: "Full kip-free range from hang to chin-over-bar.",
      safetyNotes: ["Use an assisted option if needed."],
    },
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps"],
    stabilizerMuscles: ["core"],
    commonMistakes: ["Kipping the reps", "Shrugging the shoulders"],
  },
  "ex-bulgarian-split-squat": {
    metadata: {
      difficulty: "Intermediate",
      movementPattern: "squat",
      equipment: ["dumbbell"],
      unilateral: true,
      bodyRegion: "lower-body",
      tempo: "3-1-1",
      recommendedRestSeconds: 90,
      coachTip: "Keep the front foot planted and the torso upright as you descend.",
      executionSteps: ["Place the rear foot on a bench", "Lower straight down through the front leg", "Drive through the front foot to stand"],
      breathingInstructions: "Inhale on the way down and exhale as you rise.",
      rangeOfMotion: "Full depth with a strong front-leg drive.",
      safetyNotes: ["Keep the front knee tracking over the toes."],
    },
    knowledge: {
      substitutions: [{ id: "ex-lunge", reason: "similar unilateral lower-body" }],
      variations: [{ id: "ex-elevated-split-squat" }],
      tags: ["unilateral"],
    },
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    stabilizerMuscles: ["core"],
    commonMistakes: ["Losing balance", "Allowing the front knee to cave inward"],
  },
  "ex-triceps-pushdown": {
    metadata: {
      difficulty: "Beginner",
      movementPattern: "push",
      equipment: ["cable"],
      unilateral: false,
      bodyRegion: "upper-arm",
      tempo: "2-1-2",
      recommendedRestSeconds: 60,
      coachTip: "Keep the elbows pinned to the sides and finish the rep with straight arms.",
      executionSteps: ["Set the cable at chest height", "Press the bar down without moving the elbows", "Return under control"],
      breathingInstructions: "Exhale on the push and inhale on the return.",
      rangeOfMotion: "Full elbow extension without shoulder movement.",
      safetyNotes: ["Do not lock the elbows aggressively."],
    },
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["core"],
    stabilizerMuscles: ["core"],
    commonMistakes: ["Leaning too far forward", "Flared elbows"],
  },
  "ex-competition-bench": {
    metadata: {
      difficulty: "Advanced",
      movementPattern: "push",
      equipment: ["barbell"],
      unilateral: false,
      bodyRegion: "upper-body",
      tempo: "2-1-1",
      recommendedRestSeconds: 180,
      coachTip: "Pause on the chest and keep the feet active through the press.",
      executionSteps: ["Set your feet and create a stable arch", "Touch the chest in the same spot each rep", "Drive the bar up with control"],
      breathingInstructions: "Brace before the descent and exhale as you press.",
      rangeOfMotion: "Full chest-to-lockout range with a pause.",
      safetyNotes: ["Keep the bar path over the shoulder line."],
    },
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    stabilizerMuscles: ["core"],
    commonMistakes: ["Bouncing the bar off the chest", "Losing leg drive"],
  },
  "ex-incline-db-press": {
    metadata: {
      difficulty: "Intermediate",
      movementPattern: "push",
      equipment: ["dumbbell"],
      unilateral: false,
      bodyRegion: "upper-body",
      tempo: "2-1-1",
      recommendedRestSeconds: 90,
      coachTip: "Keep the wrists stacked over the elbows and press from the upper chest.",
      executionSteps: ["Set the bench at a 30° incline", "Lower the dumbbells until the upper chest is stretched", "Press back to the start"],
      breathingInstructions: "Inhale on the descent and exhale when pressing.",
      rangeOfMotion: "Full incline press range without flaring the shoulders.",
      safetyNotes: ["Keep the shoulders packed down."],
    },
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    stabilizerMuscles: ["core"],
    commonMistakes: ["Overarching the back", "Dropping the elbows too low"],
  },
  "ex-lat-pulldown": {
    metadata: {
      difficulty: "Beginner",
      movementPattern: "pull",
      equipment: ["cable"],
      unilateral: false,
      bodyRegion: "upper-back",
      tempo: "2-1-2",
      recommendedRestSeconds: 90,
      coachTip: "Pull the elbows down and back while keeping the chest proud.",
      executionSteps: ["Sit tall and grip the bar", "Draw the bar to the upper chest", "Return under control"],
      breathingInstructions: "Exhale as you pull and inhale as you return.",
      rangeOfMotion: "Full lat stretch to upper-chest pull.",
      safetyNotes: ["Avoid leaning too far back."],
    },
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps"],
    stabilizerMuscles: ["core"],
    commonMistakes: ["Using the biceps to yank the bar", "Leaning too far back"],
  },
  "ex-lateral-raise": {
    metadata: {
      difficulty: "Beginner",
      movementPattern: "push",
      equipment: ["dumbbell"],
      unilateral: false,
      bodyRegion: "shoulders",
      tempo: "2-1-2",
      recommendedRestSeconds: 60,
      coachTip: "Lift through the shoulder line and avoid shrugging.",
      executionSteps: ["Hold the dumbbells at the sides", "Raise the arms to shoulder height", "Lower with control"],
      breathingInstructions: "Exhale as you lift and inhale on the return.",
      rangeOfMotion: "Full shoulder abduction without internal rotation.",
      safetyNotes: ["Keep the elbows soft and slightly bent."],
    },
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    stabilizerMuscles: ["core"],
    commonMistakes: ["Swinging the weights", "Shrugging the shoulders"],
  },
  "ex-face-pull": {
    metadata: {
      difficulty: "Beginner",
      movementPattern: "pull",
      equipment: ["cable"],
      unilateral: false,
      bodyRegion: "upper-back",
      tempo: "2-1-2",
      recommendedRestSeconds: 60,
      coachTip: "Lead with the elbows and externally rotate at the top.",
      executionSteps: ["Set the rope at face height", "Pull the rope toward the eyes", "Return slowly"],
      breathingInstructions: "Exhale as you pull and inhale on the return.",
      rangeOfMotion: "Full scapular retraction and external rotation.",
      safetyNotes: ["Avoid using the lower back to arch."],
    },
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["back"],
    stabilizerMuscles: ["core"],
    commonMistakes: ["Driving too hard with the elbows", "Leaning back to complete the rep"],
  },
};

/** Applies catalog enrichment defaults to an exercise definition. */
export function enrichExercise(exercise: Exercise): Exercise {
  const enrichment = EXERCISE_ENRICHMENT[exercise.id];
  const baseMetadata = createDefaultExerciseMetadata({
    ...exercise.metadata,
    ...enrichment?.metadata,
  });
  const primaryMuscles = enrichment?.primaryMuscles ?? exercise.primaryMuscles ?? [exercise.muscleGroup];
  const secondaryMuscles = enrichment?.secondaryMuscles ?? exercise.secondaryMuscles ?? [];
  const commonMistakes = enrichment?.commonMistakes ?? exercise.commonMistakes ?? [];
  const stabilizerMuscles = enrichment?.stabilizerMuscles ?? baseMetadata.stabilizerMuscles ?? [];
  const baseKnowledge = createDefaultExerciseKnowledge({
    ...baseMetadata.knowledge,
    ...enrichment?.knowledge,
  });

  return {
    ...exercise,
    primaryMuscles,
    secondaryMuscles,
    commonMistakes,
    metadata: {
      ...baseMetadata,
      knowledge: {
        ...baseKnowledge,
        primaryMuscles,
        secondaryMuscles,
        stabilizers: baseKnowledge.stabilizers ?? stabilizerMuscles,
        movementPattern: baseKnowledge.movementPattern ?? baseMetadata.movementPattern,
        equipment: baseKnowledge.equipment ?? baseMetadata.equipment,
        recommendedRestSeconds: baseKnowledge.recommendedRestSeconds ?? baseMetadata.recommendedRestSeconds,
        coachTip: baseKnowledge.coachTip ?? baseMetadata.coachTip,
        executionSteps: baseKnowledge.executionSteps ?? baseMetadata.executionSteps,
        breathing: baseKnowledge.breathing ?? baseMetadata.breathingInstructions,
        rangeOfMotion: baseKnowledge.rangeOfMotion ?? baseMetadata.rangeOfMotion,
        safetyNotes: baseKnowledge.safetyNotes ?? baseMetadata.safetyNotes,
        commonMistakes: baseKnowledge.commonMistakes ?? baseMetadata.commonMistakes,
      },
      primaryMuscles,
      secondaryMuscles,
      stabilizerMuscles,
      commonMistakes,
      difficulty: baseMetadata.difficulty,
      movementPattern: baseMetadata.movementPattern,
      equipment: baseMetadata.equipment,
      unilateral: baseMetadata.unilateral,
      bodyRegion: baseMetadata.bodyRegion,
      tempo: baseMetadata.tempo,
      recommendedRestSeconds: baseMetadata.recommendedRestSeconds,
      coachTip: baseMetadata.coachTip,
      executionSteps: baseMetadata.executionSteps,
      breathingInstructions: baseMetadata.breathingInstructions,
      rangeOfMotion: baseMetadata.rangeOfMotion,
      safetyNotes: baseMetadata.safetyNotes,
    },
  };
}
